CREATE TABLE IF NOT EXISTS "Paciente" (
	"id" UUID NOT NULL UNIQUE,
	"historia_medica" VARCHAR(255) NOT NULL UNIQUE,
	"numero_identifiacion" VARCHAR(255) NOT NULL UNIQUE,
	"tipo_documento" CHAR(1) NOT NULL,
	"nombre" VARCHAR(255) NOT NULL,
	"genero" CHAR(1) NOT NULL,
	"fecha_nacimiento" DATE NOT NULL,
	"numero_telefono" VARCHAR(255) NOT NULL,
	"direccion" VARCHAR(255) NOT NULL,
	"eliminado" BOOLEAN NOT NULL DEFAULT FALSE,
	PRIMARY KEY("id")
);

CREATE TABLE IF NOT EXISTS "Usuarios" (
	"id" UUID NOT NULL UNIQUE,
	"correo" VARCHAR(255) NOT NULL,
	"nombres" VARCHAR(255) NOT NULL,
	"apellidos" VARCHAR(255),
	"contrasena" VARCHAR(255) NOT NULL,
	"rol" VARCHAR(255) NOT NULL,
	"eliminado" BOOLEAN NOT NULL DEFAULT FALSE,
	PRIMARY KEY("id")
);




CREATE TABLE IF NOT EXISTS "Nota_Operatoria" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"dx_pre_operatorio" TEXT NOT NULL,
	"dx_post_operatorio" TEXT NOT NULL,
	"intervencion_realizada" TEXT NOT NULL,
	"fecha_comienzo" DATE NOT NULL,
	"fecha_culminacion" DATE NOT NULL,
	"hora_comienzo" TIME NOT NULL,
	"hora_culminacion" TIME NOT NULL,
	"resumen_intevencion" TEXT NOT NULL,
	-- Comentarios libres del médico sobre la intervención. Se guardan aparte
	-- del relato para poder corregirlos sin tocarlo, pero se leen como parte
	-- de él: al mostrarlo o exportarlo van al final, tras "Observaciones:".
	"comentarios" TEXT NOT NULL DEFAULT '',
	"pabellon" VARCHAR(255) NOT NULL,
	"es_electiva" BOOLEAN NOT NULL,
	"es_emergencia" BOOLEAN NOT NULL,
	"tuvo_biopsia" BOOLEAN NOT NULL,
	"anestesia" VARCHAR(255) NOT NULL,
	"id_paciente" UUID NOT NULL,
	"id_medico_encargado" UUID NOT NULL,
	"eliminado" BOOLEAN NOT NULL DEFAULT FALSE,
	"ojo" VARCHAR(3) CHECK ("ojo" IN ('OD', 'OI', 'AO')),
	"estado" VARCHAR(20) NOT NULL DEFAULT 'realizada'
		CHECK ("estado" IN ('realizada', 'diferida')),
    "tipo_lente" VARCHAR(255),
	"created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	-- Identificador que genera el dispositivo antes de tener red. Es lo que
	-- vuelve idempotente la subida: si el médico redactó la nota sin conexión y
	-- la sincronización se reintenta (se cortó a mitad, tocó dos veces el
	-- botón), el UNIQUE garantiza que la nota entre una sola vez. NULL para las
	-- notas creadas estando en línea, que nunca pasaron por la cola local.
	"client_uuid" UUID UNIQUE,
	PRIMARY KEY("id")
);




CREATE TABLE IF NOT EXISTS "Equipo_Quirurgico" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"id_nota_operatoria" INTEGER NOT NULL,
	"id_medico" UUID NOT NULL,
	"rol" VARCHAR(255) NOT NULL DEFAULT 'cirujano',
	PRIMARY KEY("id")
);




CREATE TABLE IF NOT EXISTS "Procedimientos" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	-- UNIQUE para que seed.sql se pueda correr dos veces sin duplicar el
	-- catálogo, y para que no convivan dos "Trabeculectomía".
	"intervencion" VARCHAR(255) NOT NULL UNIQUE,
	-- El relato canónico del procedimiento, que se precarga en la nota.
	"resumen" TEXT NOT NULL,
	"eliminado" BOOLEAN NOT NULL DEFAULT FALSE,
	PRIMARY KEY("id")
);




CREATE TABLE IF NOT EXISTS "Diagnosticos" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	-- La columna se llama "procedimientos" por herencia; guarda el nombre del
	-- diagnóstico ("Catarata madura"). Ver ENDPOINTS.md.
	"procedimientos" VARCHAR(255) NOT NULL UNIQUE,
	-- Un diagnóstico no tiene relato quirúrgico: aquí va la familia clínica
	-- (Catarata, Glaucoma, Pterigión...) y por eso admite NULL.
	"resumen" TEXT,
	"eliminado" BOOLEAN NOT NULL DEFAULT FALSE,
	PRIMARY KEY("id")
);




CREATE TABLE IF NOT EXISTS "Intervencion" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	-- El nombre corto, el que se ve en la lista.
	"tecnica" VARCHAR(255) NOT NULL UNIQUE,
	-- La frase que esta técnica aporta al resumen. Con el nombre solo no se
	-- puede redactar un párrafo: "Apertura de puerto principal" es la etiqueta,
	-- "se abre puerto principal en H{hora}" es lo que se escribe en la nota.
	"frase" TEXT,
	-- Los valores que cambian de una cirugía a otra, para que la pantalla los
	-- pida: [{"nombre":"hora","default":"12"}].
	"huecos" JSONB,
	"eliminado" BOOLEAN NOT NULL DEFAULT FALSE,
	PRIMARY KEY("id")
);




-- Qué técnicas ofrece cada procedimiento y en qué orden. Sin esta tabla, al
-- elegir "Trabeculectomía" el sistema no sabría qué pasos proponer.
CREATE TABLE IF NOT EXISTS "Procedimiento_Tecnica" (
	"id_procedimiento" INTEGER NOT NULL,
	"id_tecnica" INTEGER NOT NULL,
	-- El relato es cronológico: este es el lugar del paso dentro de él.
	"orden" SMALLINT NOT NULL,
	-- Si viene marcada de entrada. Las que no, quedan disponibles pero sin
	-- marcar: no todas las trabeculectomías llevan los mismos pasos.
	"por_defecto" BOOLEAN NOT NULL DEFAULT TRUE,
	PRIMARY KEY("id_procedimiento", "id_tecnica")
);



ALTER TABLE "Nota_Operatoria"
ADD FOREIGN KEY("id_paciente") REFERENCES "Paciente"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE "Nota_Operatoria"
ADD FOREIGN KEY("id_medico_encargado") REFERENCES "Usuarios"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE "Equipo_Quirurgico"
ADD FOREIGN KEY("id_nota_operatoria") REFERENCES "Nota_Operatoria"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE "Equipo_Quirurgico"
ADD FOREIGN KEY("id_medico") REFERENCES "Usuarios"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE "Procedimiento_Tecnica"
ADD FOREIGN KEY("id_procedimiento") REFERENCES "Procedimientos"("id")
ON UPDATE NO ACTION ON DELETE CASCADE;

ALTER TABLE "Procedimiento_Tecnica"
ADD FOREIGN KEY("id_tecnica") REFERENCES "Intervencion"("id")
ON UPDATE NO ACTION ON DELETE CASCADE;




-- =====================================================================
-- Alteraciones idempotentes
--
-- Los CREATE TABLE de arriba son IF NOT EXISTS: sobre una base que ya
-- existe no agregan columnas nuevas. Lo que se añada al esquema después
-- del primer despliegue va aquí, en forma repetible.
-- =====================================================================

-- Trabajo sin conexión: llave de idempotencia de la nota (ver el comentario
-- en la definición de la tabla).
ALTER TABLE "Nota_Operatoria" ADD COLUMN IF NOT EXISTS "client_uuid" UUID;

-- Comentarios del médico sobre la intervención (ver el comentario en la
-- definición de la tabla). Las notas ya registradas quedan con la cadena
-- vacía: no tenían dónde escribirlos.
ALTER TABLE "Nota_Operatoria"
	ADD COLUMN IF NOT EXISTS "comentarios" TEXT NOT NULL DEFAULT '';

-- El correo identifica al usuario al entrar, así que no puede repetirse: con
-- dos filas iguales, la sesión depende de cuál devuelva Postgres primero y la
-- contraseña buena se compara contra el hash de la otra cuenta.
--
-- La tabla original no lo exigía, de modo que puede haber duplicados ya
-- guardados. En ese caso el índice no se puede crear, y tumbar el arranque del
-- servidor por eso sería peor que el problema: se avisa en el log y se sigue.
-- Para verlos:
--   SELECT lower(btrim(correo)), count(*) FROM "Usuarios"
--   GROUP BY 1 HAVING count(*) > 1;
DO $$
BEGIN
	IF EXISTS (
		SELECT 1 FROM "Usuarios" GROUP BY lower(btrim(correo)) HAVING count(*) > 1
	) THEN
		RAISE WARNING 'Hay correos repetidos en "Usuarios": no se creó el índice único. Depúralos y vuelve a arrancar.';
	ELSE
		CREATE UNIQUE INDEX IF NOT EXISTS "Usuarios_correo_key"
			ON "Usuarios" (lower(btrim(correo)));
	END IF;
END
$$;

DO $$
BEGIN
	IF NOT EXISTS (
		SELECT 1 FROM pg_constraint WHERE conname = 'Nota_Operatoria_client_uuid_key'
	) THEN
		ALTER TABLE "Nota_Operatoria"
		ADD CONSTRAINT "Nota_Operatoria_client_uuid_key" UNIQUE ("client_uuid");
	END IF;
END
$$;


-- Legalización de la nota (v0.4.0). La nota impresa se firma, se sella y se
-- archiva en la historia; aquí queda constancia de que ese trámite ya ocurrió,
-- quién lo marcó y cuándo. Las notas anteriores quedan sin legalizar.
ALTER TABLE "Nota_Operatoria"
	ADD COLUMN IF NOT EXISTS "legalizada" BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE "Nota_Operatoria"
	ADD COLUMN IF NOT EXISTS "legalizada_en" TIMESTAMPTZ;
ALTER TABLE "Nota_Operatoria"
	ADD COLUMN IF NOT EXISTS "legalizada_por" UUID REFERENCES "Usuarios"("id");

-- Imagen de la cédula del paciente (v0.4.0), para imprimirla en la hoja de la
-- nota operatoria donde antes se pegaba la fotocopia. Va en tabla aparte para
-- que ningún listado de pacientes arrastre el binario, y en la base y no en
-- disco porque el hosting no conserva archivos entre despliegues. Una sola por
-- paciente: la cédula es del paciente, no de la cirugía.
CREATE TABLE IF NOT EXISTS "Paciente_Cedula" (
	"id_paciente"  UUID PRIMARY KEY REFERENCES "Paciente"("id"),
	"imagen"       BYTEA NOT NULL,
	"content_type" VARCHAR(50) NOT NULL,
	"tamano_bytes" INTEGER NOT NULL,
	"subida_por"   UUID NOT NULL REFERENCES "Usuarios"("id"),
	"subida_en"    TIMESTAMPTZ NOT NULL DEFAULT NOW()
);


-- =====================================================================
-- Biopsias (v0.5.0)
--
-- Una muestra enviada a anatomía patológica. Vive aparte de la nota porque
-- su ciclo (envío, informe, entrega) dura semanas y sigue cuando la nota ya
-- está cerrada y legalizada. El vínculo con la nota va en "Nota_Biopsia":
-- una cirugía puede sacar varias muestras y una muestra puede ligarse
-- también a la reintervención que motivó su resultado.
-- =====================================================================
CREATE TABLE IF NOT EXISTS "Biopsia" (
	"id"                       INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	-- Redundante con la nota, pero necesario: permite listar las biopsias de
	-- un paciente sin pasar por el puente, y garantiza que todas las notas
	-- vinculadas sean del mismo paciente (se valida al vincular).
	"id_paciente"              UUID NOT NULL REFERENCES "Paciente"("id"),
	"id_medico_responsable"    UUID NOT NULL REFERENCES "Usuarios"("id"),
	"ojo"                      VARCHAR(3) CHECK ("ojo" IN ('OD', 'OI', 'AO')),
	-- Qué se extrajo ("Pterigión nasal", "Lesión palpebral"). Texto con
	-- autocompletado en el cliente, no FK.
	"tejido"                   VARCHAR(255) NOT NULL,
	"descripcion_macroscopica" TEXT NOT NULL DEFAULT '',
	"diagnostico_presuntivo"   TEXT NOT NULL DEFAULT '',
	"fecha_toma"               DATE NOT NULL,
	"laboratorio"              VARCHAR(255),
	"fecha_envio"              DATE,
	-- Lo que asigna anatomía patológica al recibir la muestra.
	"numero_patologia"         VARCHAR(100),
	"resultado"                TEXT,
	"fecha_resultado"          DATE,
	"fecha_entrega"            DATE,
	"estado"                   VARCHAR(20) NOT NULL DEFAULT 'tomada'
		CHECK ("estado" IN ('tomada', 'enviada', 'con_resultado', 'entregada')),
	"observaciones"            TEXT NOT NULL DEFAULT '',
	"eliminado"                BOOLEAN NOT NULL DEFAULT FALSE,
	-- Idempotencia de la subida sin conexión, igual que en la nota.
	"client_uuid"              UUID UNIQUE,
	"created_at"               TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	"updated_at"               TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	PRIMARY KEY ("id")
);

-- Puente nota ↔ biopsia. La llave compuesta impide vincular dos veces la
-- misma pareja. 'origen' es la cirugía que sacó la muestra; 'seguimiento',
-- una nota posterior motivada por el resultado (reintervención).
CREATE TABLE IF NOT EXISTS "Nota_Biopsia" (
	"id_nota_operatoria" INTEGER NOT NULL REFERENCES "Nota_Operatoria"("id"),
	"id_biopsia"         INTEGER NOT NULL REFERENCES "Biopsia"("id"),
	"rol"                VARCHAR(20) NOT NULL DEFAULT 'origen'
		CHECK ("rol" IN ('origen', 'seguimiento')),
	"vinculada_por"      UUID REFERENCES "Usuarios"("id"),
	"vinculada_en"       TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	PRIMARY KEY ("id_nota_operatoria", "id_biopsia")
);

CREATE INDEX IF NOT EXISTS "Biopsia_estado_idx"       ON "Biopsia" ("estado") WHERE "eliminado" = FALSE;
CREATE INDEX IF NOT EXISTS "Biopsia_paciente_idx"     ON "Biopsia" ("id_paciente");
CREATE INDEX IF NOT EXISTS "Nota_Biopsia_biopsia_idx" ON "Nota_Biopsia" ("id_biopsia");

-- ---------------------------------------------------------------------------
-- v0.5.0: campos de la "Solicitud de biopsia o citología" (docs/Biopsia.pdf).
-- Los de la muestra y la lesión van en la biopsia; los antecedentes del
-- paciente, en el paciente. Todos opcionales: el formulario se puede seguir
-- completando a mano en lo que no se cargó.
-- ---------------------------------------------------------------------------
ALTER TABLE "Biopsia"
	ADD COLUMN IF NOT EXISTS "tipo_biopsia" VARCHAR(20)
		CHECK ("tipo_biopsia" IN ('incisional', 'excisional', 'trucut'));
ALTER TABLE "Biopsia"
	ADD COLUMN IF NOT EXISTS "tipo_citologia" VARCHAR(30)
		CHECK ("tipo_citologia" IN ('impronta', 'respronta', 'aspiracion_aguja_fina'));
ALTER TABLE "Biopsia"
	ADD COLUMN IF NOT EXISTS "centro_toma" VARCHAR(10) NOT NULL DEFAULT 'hcsc'
		CHECK ("centro_toma" IN ('hcsc', 'ivss', 'otro'));
ALTER TABLE "Biopsia"
	ADD COLUMN IF NOT EXISTS "centro_toma_otro" VARCHAR(255) NOT NULL DEFAULT '';
ALTER TABLE "Biopsia"
	ADD COLUMN IF NOT EXISTS "tipo_muestra" VARCHAR(30)
		CHECK ("tipo_muestra" IN ('cavidad_orbitaria', 'globo_ocular', 'conjuntiva', 'parpado',
			'mejilla', 'nariz', 'ceja', 'frente', 'cornea', 'otro'));
ALTER TABLE "Biopsia"
	ADD COLUMN IF NOT EXISTS "tipo_muestra_otro" VARCHAR(255) NOT NULL DEFAULT '';
-- Superior / inferior; derecho e izquierdo salen de `ojo`.
ALTER TABLE "Biopsia"
	ADD COLUMN IF NOT EXISTS "ubicacion" TEXT[] NOT NULL DEFAULT '{}';
ALTER TABLE "Biopsia"
	ADD COLUMN IF NOT EXISTS "bordes" VARCHAR(20)
		CHECK ("bordes" IN ('definidos', 'indefinidos', 'irregulares'));
ALTER TABLE "Biopsia"
	ADD COLUMN IF NOT EXISTS "color" TEXT[] NOT NULL DEFAULT '{}';
ALTER TABLE "Biopsia"
	ADD COLUMN IF NOT EXISTS "color_otro" VARCHAR(255) NOT NULL DEFAULT '';
ALTER TABLE "Biopsia"
	ADD COLUMN IF NOT EXISTS "tamano" VARCHAR(20)
		CHECK ("tamano" IN ('menor_0_5mm', '0_5_1mm', '1_2mm', '2_5mm', 'otro'));
ALTER TABLE "Biopsia"
	ADD COLUMN IF NOT EXISTS "tamano_otro" VARCHAR(100) NOT NULL DEFAULT '';
ALTER TABLE "Biopsia"
	ADD COLUMN IF NOT EXISTS "altura" VARCHAR(20)
		CHECK ("altura" IN ('plana', 'sobreelevada', 'ulcerada', 'pediculada'));
ALTER TABLE "Biopsia"
	ADD COLUMN IF NOT EXISTS "cambios_asociados" TEXT[] NOT NULL DEFAULT '{}';
-- NULL: no se preguntó. TRUE/FALSE: sí / no recibió tratamientos previos.
ALTER TABLE "Biopsia"
	ADD COLUMN IF NOT EXISTS "tratamientos_previos" BOOLEAN;
ALTER TABLE "Biopsia"
	ADD COLUMN IF NOT EXISTS "tratamientos_previos_cual" TEXT NOT NULL DEFAULT '';

ALTER TABLE "Paciente"
	ADD COLUMN IF NOT EXISTS "ocupacion" VARCHAR(255) NOT NULL DEFAULT '';
ALTER TABLE "Paciente"
	ADD COLUMN IF NOT EXISTS "raza" VARCHAR(100) NOT NULL DEFAULT '';
ALTER TABLE "Paciente"
	ADD COLUMN IF NOT EXISTS "antecedentes_oncologicos" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Paciente"
	ADD COLUMN IF NOT EXISTS "quimioterapia_ciclos" INTEGER CHECK ("quimioterapia_ciclos" >= 0);
ALTER TABLE "Paciente"
	ADD COLUMN IF NOT EXISTS "radioterapia_ciclos" INTEGER CHECK ("radioterapia_ciclos" >= 0);
-- rx, tc, rm, eco
ALTER TABLE "Paciente"
	ADD COLUMN IF NOT EXISTS "estudios_imagenes" TEXT[] NOT NULL DEFAULT '{}';
ALTER TABLE "Paciente"
	ADD COLUMN IF NOT EXISTS "hallazgo_estudios" TEXT NOT NULL DEFAULT '';
