CREATE TABLE IF NOT EXISTS "Paciente" (
	"id" UUID NOT NULL UNIQUE,
	"historia_medica" VARCHAR(255) NOT NULL UNIQUE,
	"numero_identifiacion" VARCHAR(255) NOT NULL UNIQUE,
	"tipo_documento" CHAR(1) NOT NULL,
	"nombre" VARCHAR(255) NOT NULL,
	"genero" CHAR(1) NOT NULL,
	"fecha_nacimiento" DATE NOT NULL,
	"numero_telefono" VARCHAR(255) NOT NULL,
	"direccion" VARCHAR(255) NOT NULL,
	"eliminado" BOOLEAN NOT NULL DEFAULT FALSE,
	PRIMARY KEY("id")
);

CREATE TABLE IF NOT EXISTS "Usuarios" (
	"id" UUID NOT NULL UNIQUE,
	"correo" VARCHAR(255) NOT NULL,
	"nombres" VARCHAR(255) NOT NULL,
	"apellidos" VARCHAR(255),
	"contrasena" VARCHAR(255) NOT NULL,
	"rol" VARCHAR(255) NOT NULL,
	"eliminado" BOOLEAN NOT NULL DEFAULT FALSE,
	PRIMARY KEY("id")
);




CREATE TABLE IF NOT EXISTS "Nota_Operatoria" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"dx_pre_operatorio" TEXT NOT NULL,
	"dx_post_operatorio" TEXT NOT NULL,
	"intervencion_realizada" TEXT NOT NULL,
	"fecha_comienzo" DATE NOT NULL,
	"fecha_culminacion" DATE NOT NULL,
	"hora_comienzo" TIME NOT NULL,
	"hora_culminacion" TIME NOT NULL,
	"resumen_intevencion" TEXT NOT NULL,
	"pabellon" VARCHAR(255) NOT NULL,
	"es_electiva" BOOLEAN NOT NULL,
	"es_emergencia" BOOLEAN NOT NULL,
	"tuvo_biopsia" BOOLEAN NOT NULL,
	"anestesia" VARCHAR(255) NOT NULL,
	"id_paciente" UUID NOT NULL,
	"id_medico_encargado" UUID NOT NULL,
	"eliminado" BOOLEAN NOT NULL DEFAULT FALSE,
	"ojo" VARCHAR(3) CHECK ("ojo" IN ('OD', 'OI', 'AO')),
	"estado" VARCHAR(20) NOT NULL DEFAULT 'realizada'
		CHECK ("estado" IN ('realizada', 'diferida')),
    "tipo_lente" VARCHAR(255),
	"created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	PRIMARY KEY("id")
);




CREATE TABLE IF NOT EXISTS "Equipo_Quirurgico" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"id_nota_operatoria" INTEGER NOT NULL,
	"id_medico" UUID NOT NULL,
	"rol" VARCHAR(255) NOT NULL DEFAULT 'cirujano',
	PRIMARY KEY("id")
);




CREATE TABLE IF NOT EXISTS "Procedimientos" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	-- UNIQUE para que seed.sql se pueda correr dos veces sin duplicar el
	-- catálogo, y para que no convivan dos "Trabeculectomía".
	"intervencion" VARCHAR(255) NOT NULL UNIQUE,
	-- El relato canónico del procedimiento, que se precarga en la nota.
	"resumen" TEXT NOT NULL,
	"eliminado" BOOLEAN NOT NULL DEFAULT FALSE,
	PRIMARY KEY("id")
);




CREATE TABLE IF NOT EXISTS "Diagnosticos" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	-- La columna se llama "procedimientos" por herencia; guarda el nombre del
	-- diagnóstico ("Catarata madura"). Ver ENDPOINTS.md.
	"procedimientos" VARCHAR(255) NOT NULL UNIQUE,
	-- Un diagnóstico no tiene relato quirúrgico: aquí va la familia clínica
	-- (Catarata, Glaucoma, Pterigión...) y por eso admite NULL.
	"resumen" TEXT,
	"eliminado" BOOLEAN NOT NULL DEFAULT FALSE,
	PRIMARY KEY("id")
);




CREATE TABLE IF NOT EXISTS "Intervencion" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	-- El nombre corto, el que se ve en la lista.
	"tecnica" VARCHAR(255) NOT NULL UNIQUE,
	-- La frase que esta técnica aporta al resumen. Con el nombre solo no se
	-- puede redactar un párrafo: "Apertura de puerto principal" es la etiqueta,
	-- "se abre puerto principal en H{hora}" es lo que se escribe en la nota.
	"frase" TEXT,
	-- Los valores que cambian de una cirugía a otra, para que la pantalla los
	-- pida: [{"nombre":"hora","default":"12"}].
	"huecos" JSONB,
	"eliminado" BOOLEAN NOT NULL DEFAULT FALSE,
	PRIMARY KEY("id")
);




-- Qué técnicas ofrece cada procedimiento y en qué orden. Sin esta tabla, al
-- elegir "Trabeculectomía" el sistema no sabría qué pasos proponer.
CREATE TABLE IF NOT EXISTS "Procedimiento_Tecnica" (
	"id_procedimiento" INTEGER NOT NULL,
	"id_tecnica" INTEGER NOT NULL,
	-- El relato es cronológico: este es el lugar del paso dentro de él.
	"orden" SMALLINT NOT NULL,
	-- Si viene marcada de entrada. Las que no, quedan disponibles pero sin
	-- marcar: no todas las trabeculectomías llevan los mismos pasos.
	"por_defecto" BOOLEAN NOT NULL DEFAULT TRUE,
	PRIMARY KEY("id_procedimiento", "id_tecnica")
);



ALTER TABLE "Nota_Operatoria"
ADD FOREIGN KEY("id_paciente") REFERENCES "Paciente"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE "Nota_Operatoria"
ADD FOREIGN KEY("id_medico_encargado") REFERENCES "Usuarios"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE "Equipo_Quirurgico"
ADD FOREIGN KEY("id_nota_operatoria") REFERENCES "Nota_Operatoria"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE "Equipo_Quirurgico"
ADD FOREIGN KEY("id_medico") REFERENCES "Usuarios"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE "Procedimiento_Tecnica"
ADD FOREIGN KEY("id_procedimiento") REFERENCES "Procedimientos"("id")
ON UPDATE NO ACTION ON DELETE CASCADE;

ALTER TABLE "Procedimiento_Tecnica"
ADD FOREIGN KEY("id_tecnica") REFERENCES "Intervencion"("id")
ON UPDATE NO ACTION ON DELETE CASCADE;
