BEGIN;
    DROP TABLE IF EXISTS equipo_quirurgico CASCADE;
    DROP TABLE IF EXISTS notas CASCADE;
    DROP TABLE IF EXISTS admins CASCADE;
    DROP TABLE IF EXISTS pacientes CASCADE;
    DROP TABLE IF EXISTS usuarios CASCADE;
END;
