-- Catálogo clínico del servicio de oftalmología del HCSC.
-- Generado a partir de las 169 notas operatorias de docs/*.pptx.
-- Ver docs/catalogos.md (las listas) y docs/catalogo-clinico.md (el análisis).
--
-- Es idempotente: se apoya en los UNIQUE de create.sql, así que correrlo dos
-- veces no duplica nada y no pisa lo que el admin haya editado (HU-20).

BEGIN;

-- =====================================================================
-- Diagnósticos (54) — qué se vio (HU-19)
-- =====================================================================
INSERT INTO "Diagnosticos" (procedimientos, resumen) VALUES
  ('Catarata', 'Catarata'),
  ('Catarata madura', 'Catarata'),
  ('Catarata blanca', 'Catarata'),
  ('Catarata senil', 'Catarata'),
  ('Afaquia', 'Catarata'),
  ('Pseudofaquia', 'Catarata'),
  ('Uveítis pseudofáquica', 'Catarata'),
  ('Glaucoma primario de ángulo estrecho', 'Glaucoma'),
  ('Glaucoma congénito', 'Glaucoma'),
  ('Glaucoma crónico', 'Glaucoma'),
  ('Glaucoma agudo', 'Glaucoma'),
  ('Glaucoma primario de ángulo abierto', 'Glaucoma'),
  ('Glaucoma agudo de ángulo cerrado', 'Glaucoma'),
  ('Glaucoma por cierre de ángulo', 'Glaucoma'),
  ('Glaucoma facomórfico', 'Glaucoma'),
  ('Glaucoma neovascular', 'Glaucoma'),
  ('Glaucoma congénito asociado a síndrome de Down', 'Glaucoma'),
  ('Glaucoma absoluto', 'Glaucoma'),
  ('Glaucoma infantil', 'Glaucoma'),
  ('Glaucoma facoanafiláctico', 'Glaucoma'),
  ('Glaucoma secundario', 'Glaucoma'),
  ('Glaucoma secundario a luxación de LIO a cámara vítrea', 'Glaucoma'),
  ('Glaucoma crónico + catarata', 'Glaucoma'),
  ('Hipertensión ocular secundaria a luxación de LIO en cámara anterior', 'Glaucoma'),
  ('Ojo ciego no doloroso', 'Glaucoma'),
  ('Pterigión nasal grado II', 'Pterigión'),
  ('Pterigión nasal grado III', 'Pterigión'),
  ('Pterigión temporal grado II', 'Pterigión'),
  ('Pterigión temporal grado III', 'Pterigión'),
  ('Pterigión temporal grado IV', 'Pterigión'),
  ('Endotropía infantil', 'Estrabismo'),
  ('Endotropía infantil de aparición precoz', 'Estrabismo'),
  ('Endotropía congénita de aparición precoz', 'Estrabismo'),
  ('Endotropía residual', 'Estrabismo'),
  ('Endotropía asociada a miopía', 'Estrabismo'),
  ('Exotropía por exceso de divergencia', 'Estrabismo'),
  ('Exotropía consecutiva', 'Estrabismo'),
  ('Desviación vertical', 'Estrabismo'),
  ('Epitelización de vía lagrimal', 'Vía lagrimal'),
  ('Epitelización de puntos lagrimales', 'Vía lagrimal'),
  ('Traumatismo ocular contuso', 'Trauma'),
  ('Traumatismo ocular abierto penetrante', 'Trauma'),
  ('Prolapso uveal', 'Trauma'),
  ('Queratitis herpética', 'Trauma'),
  ('Queratopatía bullosa', 'Trauma'),
  ('Chalazión palpebral', 'Anexos'),
  ('Quiste sebáceo palpebral', 'Anexos'),
  ('Granuloma conjuntival', 'Anexos'),
  ('Retiro de material médico quirúrgico', 'Postquirúrgico'),
  ('Postoperatorio tardío de extracción extracapsular de LIO', 'Postquirúrgico'),
  ('Postoperatorio tardío de extracción extracapsular de LIO anclado a esclera', 'Postquirúrgico'),
  ('Postoperatorio de colocación de válvula de drenaje', 'Postquirúrgico'),
  ('Postoperatorio de aspiración de masas cristalinianas', 'Postquirúrgico'),
  ('Postoperatorio tardío de EECC + vitrectomía manual anterior + afaquia', 'Postquirúrgico')
ON CONFLICT (procedimientos) DO NOTHING;

-- =====================================================================
-- Procedimientos (42) — cómo se trató
-- El resumen queda precargado y editable: es el ~80 % del texto que hoy
-- se copia y pega entre notas.
-- =====================================================================
INSERT INTO "Procedimientos" (intervencion, resumen) VALUES
  ('Extracción extracapsular de catarata + implante de LIO',
   'Bajo anestesia local, previa asepsia y antisepsia del área operatoria, colocación de campos quirúrgicos estériles, Tegaderm, blefaróstato, aclaramiento con solución Ringer lactato, se procede a realizar perilimbotomía superior en 180°, cauterización de vasos sangrantes, se delinea surco con cuchillete 15°, se profundiza con crescent, se abre puerto principal en H12, inyección de azul tripán con posterior aclaramiento, se inyecta viscoelástico en cámara anterior, capsulotomía anterior en abrelatas, extracción de núcleo con maniobra de presión contra presión, implante de LIO en saco capsular, remoción de restos cristalinianos con cánula de Simcoe, remoción de viscoelástico, se invaginan puntos, se inyecta miochol, se administra antibiótico subconjuntival, antibiótico tópico, parchado ocular, acto culminado sin complicaciones.'),
  ('Extracción extracapsular + trabeculectomía + implante de LIO',
   'Bajo anestesia local, previa asepsia y antisepsia del área operatoria, colocación de campos quirúrgicos estériles, Tegaderm, blefaróstato, aclaramiento con solución Ringer lactato, se procede a realizar perilimbotomía superior en 180°, cauterización de vasos sangrantes, se profundiza con crescent, se abre puerto principal en H12, inyección de azul tripán con posterior aclaramiento, se inyecta viscoelástico en cámara anterior, capsulotomía anterior en abrelatas, remoción de restos cristalinianos con cánula de Simcoe, remoción de viscoelástico, esclerotomía con cuchillete 15° en charnela cuadrada, se invaginan puntos, se inyecta miochol, se administra mitomicina tópica durante 3 minutos, se procede a aperturar puertos laterales H3 y H9, iridotomía con pinza punch de Kelly, se administra antibiótico subconjuntival, antibiótico tópico, parchado ocular, acto culminado sin complicaciones.'),
  ('Extracción extracapsular + afaquia',
   'Bajo anestesia tópica, previa asepsia y antisepsia del área operatoria, colocación de campos quirúrgicos estériles, Tegaderm, blefaróstato, se procede a realizar perilimbotomía superior en 180°, cauterización de vasos sangrantes, se delinea surco con cuchillete 15°, se profundiza con crescent, se abre puerto principal en H12, inyección de azul tripán con posterior aclaramiento, se inyecta viscoelástico en cámara anterior, capsulotomía anterior en abrelatas, extracción de núcleo con maniobra de presión contra presión, se invaginan puntos, se inyecta miochol, se administra antibiótico subconjuntival, antibiótico tópico, parchado ocular, acto culminado sin complicaciones.'),
  ('Facoemulsificación + implante de LIO',
   'Bajo anestesia tópica, previa asepsia y antisepsia del área operatoria, colocación de campos quirúrgicos estériles, Tegaderm, blefaróstato, se procede a aperturar puertos laterales H3 y H9, inyección de azul tripán con posterior aclaramiento, se inyecta viscoelástico en cámara anterior, se abre puerto principal en H12, capsulorrexis circular continua, hidrodisección, facoemulsificación bajo técnica de stop and chop, remoción de viscoelástico, se hidratan puertos laterales, se inyecta miochol, se administra antibiótico subconjuntival, antibiótico tópico, parchado ocular, acto culminado sin complicaciones.'),
  ('Explante de LIO',
   'Bajo anestesia local, previa asepsia y antisepsia del área operatoria, colocación de campos quirúrgicos estériles, Tegaderm, blefaróstato, aclaramiento con solución Ringer lactato, se administra antibiótico subconjuntival, antibiótico tópico, parchado ocular, acto culminado sin complicaciones.'),
  ('Implante secundario de LIO anclado a esclera',
   'Bajo anestesia local y peribulbar, previa asepsia y antisepsia del área operatoria, colocación de campos quirúrgicos estériles, Tegaderm, blefaróstato, se abre puerto principal en H12, se inyecta viscoelástico en cámara anterior, se invaginan puntos, se coloca dexametasona subconjuntival, antibiótico tópico, parchado ocular, acto culminado sin complicaciones.'),
  ('Extracción extracapsular + implante de LIO anclado a esclera',
   'Bajo anestesia local, previa asepsia y antisepsia del área operatoria, colocación de campos quirúrgicos estériles, Tegaderm, blefaróstato, aclaramiento con solución Ringer lactato, se procede a realizar perilimbotomía superior en 180°, cauterización de vasos sangrantes, se abre puerto principal en H12, inyección de azul tripán con posterior aclaramiento, se inyecta viscoelástico en cámara anterior, capsulotomía anterior en abrelatas, remoción de restos cristalinianos con cánula de Simcoe, remoción de viscoelástico, se invaginan puntos, se inyecta miochol, se administra antibiótico subconjuntival, antibiótico tópico, parchado ocular, acto culminado sin complicaciones.'),
  ('Extracción extracapsular + vitrectomía anterior',
   'Bajo anestesia tópica, previa asepsia y antisepsia del área operatoria, colocación de campos quirúrgicos estériles, Tegaderm, blefaróstato, se procede a realizar perilimbotomía superior en 180°, cauterización de vasos sangrantes, se delinea surco con cuchillete 15°, se profundiza con crescent, se abre puerto principal en H12, inyección de azul tripán con posterior aclaramiento, se inyecta viscoelástico en cámara anterior, capsulotomía anterior en abrelatas, extracción de núcleo con maniobra de presión contra presión, se invaginan puntos, se inyecta miochol, se administra antibiótico subconjuntival, antibiótico tópico, parchado ocular, acto culminado sin complicaciones.'),
  ('Aspiración de masas cristalinianas',
   'Bajo anestesia local, previa asepsia y antisepsia del área operatoria, colocación de campos quirúrgicos estériles, Tegaderm, blefaróstato, se inyecta viscoelástico en cámara anterior, remoción de restos cristalinianos con cánula de Simcoe, remoción de viscoelástico, se invaginan puntos, se inyecta miochol, se administra antibiótico subconjuntival, antibiótico tópico, parchado ocular, acto culminado sin complicaciones.'),
  ('Reposición pupilar + aspiración de masas cristalinianas',
   'Bajo anestesia local, previa asepsia y antisepsia del área operatoria, colocación de campos quirúrgicos estériles, Tegaderm, blefaróstato, se inyecta viscoelástico en cámara anterior, remoción de restos cristalinianos con cánula de Simcoe, remoción de viscoelástico, se invaginan puntos, se inyecta miochol, se administra antibiótico subconjuntival, antibiótico tópico, parchado ocular, acto culminado sin complicaciones.'),
  ('Trabeculectomía',
   'Bajo anestesia local, previa asepsia y antisepsia del área operatoria, colocación de campos quirúrgicos estériles, Tegaderm, blefaróstato, se procede a realizar lavado ocular con iodopovidona al 2 %, posterior lavado con 80 cc de solución Ringer, aclaramiento con solución Ringer lactato, cauterización de vasos sangrantes, se divulsiona conjuntiva en base de fórnix, tenectomía, esclerotomía con cuchillete 15° en charnela cuadrada, se profundiza con crescent, se administra mitomicina tópica durante 3 minutos, se procede a aperturar puertos laterales H3 y H9, se realiza iridectomía en H12, iridotomía con pinza punch de Kelly, asepsia final, antibiótico tópico, parchado ocular, acto culminado sin complicaciones.'),
  ('Trabeculectomía minifiltrante',
   'Bajo anestesia general, previa asepsia y antisepsia del área operatoria, colocación de campos quirúrgicos estériles, Tegaderm, blefaróstato, cauterización de vasos sangrantes, se profundiza con crescent, se administra mitomicina tópica durante 3 minutos, aclaramiento con solución Ringer lactato, se procede a aperturar puertos laterales H3 y H9, se inyecta miochol, iridotomía con pinza punch de Kelly, se realiza sutura epiescleral de fijación muscular, asepsia final, antibiótico tópico, parchado ocular, acto culminado sin complicaciones.'),
  ('Iridectomía',
   'Bajo anestesia local, previa asepsia y antisepsia del área operatoria, colocación de campos quirúrgicos estériles, blefaróstato, se procede a realizar perilimbotomía superior en 180°, se delinea surco con cuchillete 15°, se profundiza con crescent, se abre puerto principal en H12, se inyecta viscoelástico en cámara anterior, se realiza iridectomía en H12, remoción de viscoelástico, se administra antibiótico subconjuntival, antibiótico tópico, parchado ocular, acto culminado sin complicaciones.'),
  ('Needling + mitomicina C',
   'Colocación de anestesia subtenon en región nasal inferior, previa asepsia y antisepsia del área operatoria, colocación de campos quirúrgicos estériles, Tegaderm, blefaróstato, aclaramiento con solución Ringer lactato, reposición de úvea con espátula de iris, se administra mitomicina tópica durante 3 minutos, se realiza punción subconjuntival con aguja de insulina permeabilizando charnela, antibiótico tópico, parchado ocular, acto culminado sin complicaciones.'),
  ('Colocación de válvula de drenaje',
   'Colocación de anestesia subtenon en región nasal inferior, previa asepsia y antisepsia del área operatoria, colocación de campos quirúrgicos estériles, Tegaderm, blefaróstato, se procede a aperturar puertos laterales H3 y H9, cauterización de vasos sangrantes, se realiza sutura epiescleral de fijación muscular, se posiciona válvula retromuscular a 8 mm del limbo, asepsia final, antibiótico tópico, parchado ocular, acto culminado sin complicaciones.'),
  ('Reposición de válvula de drenaje',
   'Bajo anestesia tópica, previa asepsia y antisepsia del área operatoria, colocación de campos quirúrgicos estériles, Tegaderm, blefaróstato, se procede a aperturar puertos laterales H3 y H9, asepsia final, antibiótico tópico, parchado ocular, acto culminado sin complicaciones.'),
  ('Trabeculectomía + retiro de material quirúrgico',
   'Bajo anestesia local, previa asepsia y antisepsia del área operatoria, colocación de campos quirúrgicos estériles, Tegaderm, blefaróstato, se procede a realizar lavado ocular con iodopovidona al 2 %, posterior lavado con 80 cc de solución Ringer, aclaramiento con solución Ringer lactato, se divulsiona conjuntiva en base de fórnix, tenectomía, cauterización de vasos sangrantes, esclerotomía con cuchillete 15° en charnela cuadrada, se administra mitomicina tópica durante 3 minutos, se procede a aperturar puertos laterales H3 y H9, iridotomía con pinza punch de Kelly, antibiótico tópico, parchado ocular, acto culminado sin complicaciones.'),
  ('Exéresis de pterigión',
   'Bajo anestesia local, previa asepsia y antisepsia del área operatoria, colocación de campos quirúrgicos estériles, blefaróstato, se realiza lavado de superficie con iodopovidona al 10 % durante 3 minutos, se infiltra 0.3 cc de lidocaína subconjuntival, queratoplastia de cabeza de pterigión, se realiza fijación de plastia mediante 7 puntos separados de nylon 10-0, tenectomía, verificación de hemostasia, antibiótico tópico, parchado ocular, acto culminado sin complicaciones.'),
  ('Retroceso del recto medio',
   'Bajo anestesia general, previa asepsia y antisepsia del área operatoria, colocación de campos quirúrgicos estériles, Tegaderm, blefaróstato, se realiza lavado de superficie con iodopovidona al 10 % durante 3 minutos, se procede a fijar globo ocular en H12 y H6 con sutura seda 4-0, se realiza bolsillo conjuntival, se procede a realizar incisiones relajantes, se corta músculo sobrante con tijera Westcott, para realización de sutura flotante, se coloca dexametasona subconjuntival, se realiza sutura epiescleral de fijación muscular, antibiótico tópico, parchado ocular, acto culminado sin complicaciones.'),
  ('Resección del recto lateral',
   'Bajo anestesia general, previa asepsia y antisepsia del área operatoria, colocación de campos quirúrgicos estériles, Tegaderm, blefaróstato, se procede a referir conjuntiva con sutura seda 4-0, se procede a realizar incisiones relajantes, se realiza sutura epiescleral de fijación muscular, se corta músculo sobrante con tijera Westcott, se coloca dexametasona subconjuntival, antibiótico tópico, parchado ocular, acto culminado sin complicaciones.'),
  ('Miectomía de oblicuo inferior',
   'Bajo anestesia general, previa asepsia y antisepsia del área operatoria, colocación de campos quirúrgicos estériles, Tegaderm, blefaróstato, aclaramiento con solución Ringer lactato, se realiza sutura epiescleral de fijación muscular, cauterización de vasos sangrantes, verificación de hemostasia, se coloca dexametasona subconjuntival, antibiótico tópico, parchado ocular, acto culminado sin complicaciones.'),
  ('Retroceso del recto lateral',
   'Bajo anestesia general, previa asepsia y antisepsia del área operatoria, colocación de campos quirúrgicos estériles, Tegaderm, blefaróstato, se realiza lavado de superficie con iodopovidona al 10 % durante 3 minutos, se procede a fijar globo ocular en H12 y H6 con sutura seda 4-0, se realiza bolsillo conjuntival, se procede a realizar incisiones relajantes, se corta músculo sobrante con tijera Westcott, para realización de sutura flotante, se realiza sutura epiescleral de fijación muscular, se coloca dexametasona subconjuntival, antibiótico tópico, parchado ocular, acto culminado sin complicaciones.'),
  ('Resección del recto medio',
   'Bajo anestesia general, previa asepsia y antisepsia del área operatoria, colocación de campos quirúrgicos estériles, Tegaderm, blefaróstato, se procede a referir conjuntiva con sutura seda 4-0, se procede a realizar incisiones relajantes, se realiza sutura epiescleral de fijación muscular, se corta músculo sobrante con tijera Westcott, se coloca dexametasona subconjuntival, antibiótico tópico, parchado ocular, acto culminado sin complicaciones.'),
  ('Resección y avance del recto medio',
   'Bajo anestesia general, previa asepsia y antisepsia del área operatoria, colocación de campos quirúrgicos estériles, Tegaderm, blefaróstato, se procede a referir conjuntiva con sutura seda 4-0, se procede a realizar incisiones relajantes, se realiza sutura epiescleral de fijación muscular, se corta músculo sobrante con tijera Westcott, se coloca dexametasona subconjuntival, antibiótico tópico, parchado ocular, acto culminado sin complicaciones.'),
  ('Retroceso + resección del recto medio',
   'Bajo anestesia general, previa asepsia y antisepsia del área operatoria, colocación de campos quirúrgicos estériles, Tegaderm, blefaróstato, se realiza lavado de superficie con iodopovidona al 10 % durante 3 minutos, se procede a fijar globo ocular en H12 y H6 con sutura seda 4-0, se realiza bolsillo conjuntival, se procede a realizar incisiones relajantes, se corta músculo sobrante con tijera Westcott, para realización de sutura flotante, se realiza sutura epiescleral de fijación muscular, se coloca dexametasona subconjuntival, antibiótico tópico, parchado ocular, acto culminado sin complicaciones.'),
  ('Retroceso del músculo oblicuo inferior',
   'Bajo anestesia general, previa asepsia y antisepsia del área operatoria, colocación de campos quirúrgicos estériles, Tegaderm, blefaróstato, se realiza lavado de superficie con iodopovidona al 10 % durante 3 minutos, se procede a fijar globo ocular en H12 y H6 con sutura seda 4-0, se realiza bolsillo conjuntival, se procede a realizar incisiones relajantes, se corta músculo sobrante con tijera Westcott, para realización de sutura flotante, se realiza sutura epiescleral de fijación muscular, se coloca dexametasona subconjuntival, antibiótico tópico, parchado ocular, acto culminado sin complicaciones.'),
  ('Retroceso bilateral de rectos medios + miectomía bilateral de oblicuos inferiores',
   'Bajo anestesia general, previa asepsia y antisepsia del área operatoria, colocación de campos quirúrgicos estériles, Tegaderm, blefaróstato, se procede a referir conjuntiva con sutura seda 4-0, se procede a realizar incisiones relajantes, se realiza sutura epiescleral de fijación muscular, cauterización de vasos sangrantes, se coloca dexametasona subconjuntival, antibiótico tópico, parchado ocular, acto culminado sin complicaciones.'),
  ('Mioescleropexia retroecuatorial',
   'Bajo anestesia general, previa asepsia y antisepsia del área operatoria, colocación de campos quirúrgicos estériles, Tegaderm, blefaróstato, se realiza lavado de superficie con iodopovidona al 10 % durante 3 minutos, se procede a fijar globo ocular en H12 y H6 con sutura seda 4-0, se realiza sutura epiescleral de fijación muscular, antibiótico tópico, parchado ocular, acto culminado sin complicaciones.'),
  ('Transposición muscular tipo Jansen',
   'Bajo anestesia general, previa asepsia y antisepsia del área operatoria, colocación de campos quirúrgicos estériles, Tegaderm, blefaróstato, se realiza lavado de superficie con iodopovidona al 10 % durante 3 minutos, se procede a fijar globo ocular en H12 y H6 con sutura seda 4-0, se realiza sutura epiescleral de fijación muscular, se coloca dexametasona subconjuntival, antibiótico tópico, parchado ocular, acto culminado sin complicaciones.'),
  ('Recanalización de vías lagrimales',
   'Bajo anestesia local, previa asepsia y antisepsia del área operatoria, colocación de campos quirúrgicos estériles, blefaróstato, se realiza lavado de superficie con iodopovidona al 10 % durante 3 minutos, se procede a dilatar puntos lagrimales superiores e inferiores con dilatador de vía lagrimal, se procede a permeabilizar vía lagrimal introduciendo sonda de Bowman N.° 2, se comprueba permeabilidad introduciendo cánula unida a inyectadora cargada con 5 cc de solución salina al 0,9 %, antibiótico tópico, parchado ocular, acto culminado sin complicaciones.'),
  ('Puntoplastia',
   'Bajo anestesia local, previa asepsia y antisepsia del área operatoria, colocación de campos quirúrgicos estériles, se procede a dilatar puntos lagrimales superiores e inferiores con dilatador de vía lagrimal, se procede a permeabilizar vía lagrimal introduciendo sonda de Bowman N.° 2, se comprueba permeabilidad introduciendo cánula unida a inyectadora cargada con 5 cc de solución salina al 0,9 %, asepsia final, antibiótico tópico, parchado ocular, acto culminado sin complicaciones.'),
  ('Sondaje de vía lagrimal',
   'Bajo anestesia local, previa asepsia y antisepsia del área operatoria, colocación de campos quirúrgicos estériles, se procede a dilatar puntos lagrimales superiores e inferiores con dilatador de vía lagrimal, se procede a permeabilizar vía lagrimal introduciendo sonda de Bowman N.° 2, se comprueba permeabilidad introduciendo cánula unida a inyectadora cargada con 5 cc de solución salina al 0,9 %, asepsia final, antibiótico tópico, parchado ocular, acto culminado sin complicaciones.'),
  ('Exploración quirúrgica',
   'Bajo anestesia local, previa asepsia y antisepsia del área operatoria, colocación de campos quirúrgicos estériles, Tegaderm, blefaróstato, se realiza lavado de superficie con iodopovidona al 10 % durante 3 minutos, aclaramiento con solución Ringer lactato, antibiótico tópico, parchado ocular, acto culminado sin complicaciones.'),
  ('Reposición uveal + rafia corneoescleral',
   'Bajo anestesia local, previa asepsia y antisepsia del área operatoria, colocación de campos quirúrgicos estériles, Tegaderm, blefaróstato, se profundiza con crescent, se inyecta viscoelástico en cámara anterior, reposición de úvea con espátula de iris, se invaginan puntos, se administra antibiótico subconjuntival, antibiótico tópico, parchado ocular, acto culminado sin complicaciones.'),
  ('Recubrimiento conjuntival',
   'Bajo anestesia tópica, previa asepsia y antisepsia del área operatoria, colocación de campos quirúrgicos estériles, Tegaderm, blefaróstato, se realiza lavado de superficie con iodopovidona al 10 % durante 3 minutos, aclaramiento con solución Ringer lactato, instilación de alcohol absoluto sobre la lesión corneal y posterior desepitelización con hojilla de bisturí n.° 15, se realiza colgajo conjuntival bipediculado, se avanza el colgajo sobre la lesión corneal y se fija con vicryl 7-0, se administra antibiótico subconjuntival, antibiótico tópico, parchado ocular, acto culminado sin complicaciones.'),
  ('Reposición uveal',
   'Bajo anestesia local, previa asepsia y antisepsia del área operatoria, colocación de campos quirúrgicos estériles, blefaróstato, aclaramiento con solución Ringer lactato, reposición de úvea con espátula de iris, se invaginan puntos, antibiótico tópico, parchado ocular, acto culminado sin complicaciones.'),
  ('Recubrimiento conjuntival bipediculado',
   'Bajo anestesia tópica, previa asepsia y antisepsia del área operatoria, colocación de campos quirúrgicos estériles, Tegaderm, se realiza lavado de superficie con iodopovidona al 10 % durante 3 minutos, aclaramiento con solución Ringer lactato, instilación de alcohol absoluto sobre la lesión corneal y posterior desepitelización con hojilla de bisturí n.° 15, se avanza el colgajo sobre la lesión corneal y se fija con vicryl 7-0, antibiótico tópico, parchado ocular, acto culminado sin complicaciones.'),
  ('Drenaje de chalazión',
   'Bajo anestesia local, previa asepsia y antisepsia del área operatoria, colocación de campos quirúrgicos estériles, se procede a realizar colocación y fijación de pinza de chalazión delimitando el área de lesión, se realiza incisión vertical de 1 mm en región subtarsal, se realiza limpieza del área con cureta de chalazión, se coloca dexametasona subconjuntival, antibiótico tópico, parchado ocular, acto culminado sin complicaciones.'),
  ('Exéresis de quiste sebáceo palpebral',
   'Bajo anestesia general, previa asepsia y antisepsia del área operatoria, colocación de campos quirúrgicos estériles, cauterización de vasos sangrantes, asepsia final, antibiótico tópico, parchado ocular, acto culminado sin complicaciones.'),
  ('Exéresis de granuloma',
   'Bajo anestesia local, previa asepsia y antisepsia del área operatoria, colocación de campos quirúrgicos estériles, blefaróstato, se realiza lavado de superficie con iodopovidona al 10 % durante 3 minutos, se infiltra 0.3 cc de lidocaína subconjuntival, tenectomía, verificación de hemostasia, antibiótico tópico, parchado ocular, acto culminado sin complicaciones.'),
  ('Rafia de herida palpebral',
   'Bajo anestesia local, previa asepsia y antisepsia del área operatoria, verificación de hemostasia, antibiótico tópico, parchado ocular, acto culminado sin complicaciones.'),
  ('Retiro de material médico quirúrgico',
   'Bajo anestesia local, previa asepsia y antisepsia del área operatoria, colocación de campos quirúrgicos estériles, blefaróstato, Tegaderm, antibiótico tópico, parchado ocular, acto culminado sin complicaciones.')
ON CONFLICT (intervencion) DO NOTHING;

-- =====================================================================
-- Técnicas (71) — el paso concreto dentro del procedimiento.
-- `frase` es lo que se inserta en el resumen; `huecos` son los valores que
-- cambian de una cirugía a otra (hora del reloj, número de puntos, calibre).
-- =====================================================================
INSERT INTO "Intervencion" (tecnica, frase, huecos) VALUES
  ('Asepsia y antisepsia del área operatoria',
   'previa asepsia y antisepsia del área operatoria', NULL),
  ('Colocación de campos quirúrgicos estériles',
   'colocación de campos quirúrgicos estériles', NULL),
  ('Tegaderm',
   'Tegaderm', NULL),
  ('Blefaróstato',
   'blefaróstato', NULL),
  ('Lavado de superficie con iodopovidona al 2 %',
   'se procede a realizar lavado ocular con iodopovidona al 2 %, posterior lavado con {volumen} cc de solución Ringer', '[{"nombre":"volumen","default":"80"}]'::jsonb),
  ('Lavado de superficie con iodopovidona al 10 %',
   'se realiza lavado de superficie con iodopovidona al 10 % durante {minutos} minutos', '[{"nombre":"minutos","default":"3"}]'::jsonb),
  ('Aclaramiento con solución Ringer lactato',
   'aclaramiento con solución Ringer lactato', NULL),
  ('Cauterización de vasos sangrantes',
   'cauterización de vasos sangrantes', NULL),
  ('Verificación de hemostasia',
   'verificación de hemostasia', NULL),
  ('Asepsia final',
   'asepsia final', NULL),
  ('Antibiótico subconjuntival',
   'se administra antibiótico subconjuntival', NULL),
  ('Antibiótico tópico',
   'antibiótico tópico', NULL),
  ('Parchado ocular',
   'parchado ocular', NULL),
  ('Anestesia local',
   'bajo anestesia local', NULL),
  ('Anestesia local peribulbar',
   'bajo anestesia local y peribulbar', NULL),
  ('Anestesia retrobulbar',
   'bajo anestesia retrobulbar', NULL),
  ('Anestesia general',
   'bajo anestesia general', NULL),
  ('Anestesia tópica',
   'bajo anestesia tópica', NULL),
  ('Anestesia subtenon',
   'colocación de anestesia subtenon en {region}', '[{"nombre":"region","default":"región nasal inferior"}]'::jsonb),
  ('Sedación',
   'bajo sedación', NULL),
  ('Infiltración de lidocaína subconjuntival',
   'se infiltra {dosis} cc de lidocaína subconjuntival', '[{"nombre":"dosis","default":"0.3"}]'::jsonb),
  ('Perilimbotomía superior en 180°',
   'se procede a realizar perilimbotomía superior en {grados}°', '[{"nombre":"grados","default":"180"}]'::jsonb),
  ('Perilimbotomía inferior',
   'se procede a realizar perilimbotomía inferior', NULL),
  ('Divulsión de conjuntiva en base de fórnix',
   'se divulsiona conjuntiva en base de fórnix', NULL),
  ('Bolsillo conjuntival',
   'se realiza bolsillo conjuntival', NULL),
  ('Incisiones relajantes',
   'se procede a realizar incisiones relajantes', NULL),
  ('Tenectomía',
   'tenectomía', NULL),
  ('Delineado de surco con cuchillete 15°',
   'se delinea surco con cuchillete {calibre}°', '[{"nombre":"calibre","default":"15"}]'::jsonb),
  ('Profundización con crescent',
   'se profundiza con crescent', NULL),
  ('Apertura de puerto principal en H11 / H12',
   'se abre puerto principal en H{hora}', '[{"nombre":"hora","default":"12"}]'::jsonb),
  ('Apertura de puertos laterales H3 y H9',
   'se procede a aperturar puertos laterales H{lateral1} y H{lateral2}', '[{"nombre":"lateral1","default":"3"},{"nombre":"lateral2","default":"9"}]'::jsonb),
  ('Hidratación de puertos laterales',
   'se hidratan puertos laterales', NULL),
  ('Tinción con azul tripán',
   'inyección de azul tripán con posterior aclaramiento', NULL),
  ('Inyección de viscoelástico en cámara anterior',
   'se inyecta viscoelástico en cámara anterior', NULL),
  ('Remoción de viscoelástico',
   'remoción de viscoelástico', NULL),
  ('Capsulotomía anterior en abrelatas',
   'capsulotomía anterior en abrelatas', NULL),
  ('Capsulorrexis circular continua',
   'capsulorrexis circular continua', NULL),
  ('Hidrodisección',
   'hidrodisección', NULL),
  ('Facoemulsificación con técnica *stop and chop*',
   'facoemulsificación bajo técnica de stop and chop', NULL),
  ('Extracción de núcleo por presión-contrapresión',
   'extracción de núcleo con maniobra de presión contra presión', NULL),
  ('Remoción de restos corticales con cánula de Simcoe',
   'remoción de restos cristalinianos con cánula de Simcoe', NULL),
  ('Implante de LIO en saco capsular',
   'implante de LIO en saco capsular {poder}', '[{"nombre":"poder","default":""}]'::jsonb),
  ('Implante de LIO anclado a esclera en H12',
   'implante de LIO anclado a esclera en H{hora}', '[{"nombre":"hora","default":"12"}]'::jsonb),
  ('Invaginación de puntos',
   'se invaginan puntos', NULL),
  ('Inyección de miochol',
   'se inyecta miochol', NULL),
  ('Esclerotomía en charnela cuadrada',
   'esclerotomía con cuchillete {calibre}° en charnela cuadrada', '[{"nombre":"calibre","default":"15"}]'::jsonb),
  ('Mitomicina C tópica durante 3 minutos',
   'se administra mitomicina tópica durante {minutos} minutos', '[{"nombre":"minutos","default":"3"}]'::jsonb),
  ('Iridotomía con pinza punch de Kelly',
   'iridotomía con pinza punch de Kelly', NULL),
  ('Iridectomía en H12',
   'se realiza iridectomía en H{hora}', '[{"nombre":"hora","default":"12"}]'::jsonb),
  ('Needling con aguja de insulina',
   'se realiza punción subconjuntival con aguja de insulina permeabilizando charnela', NULL),
  ('Posicionamiento de válvula retromuscular a 8 mm del limbo',
   'se posiciona válvula retromuscular a {distancia} mm del limbo', '[{"nombre":"distancia","default":"8"}]'::jsonb),
  ('Queratoplastia de cabeza de pterigión',
   'queratoplastia de cabeza de pterigión', NULL),
  ('Autoinjerto conjuntival',
   'se realiza fijación de plastia mediante {puntos} puntos separados de nylon 10-0', '[{"nombre":"puntos","default":"7"}]'::jsonb),
  ('Colocación de membrana amniótica',
   'se procede a realizar fijación de membrana amniótica mediante {puntos} puntos separados de nylon 10-0', '[{"nombre":"puntos","default":"5"}]'::jsonb),
  ('Referencia de conjuntiva con seda 4-0',
   'se procede a referir conjuntiva con sutura seda {calibre}', '[{"nombre":"calibre","default":"4-0"}]'::jsonb),
  ('Fijación del globo ocular en H12 y H6',
   'se procede a fijar globo ocular en H12 y H6 con sutura seda {calibre}', '[{"nombre":"calibre","default":"4-0"}]'::jsonb),
  ('Desinserción muscular con tijera Westcott',
   'se corta músculo sobrante con tijera Westcott', NULL),
  ('Sutura flotante',
   'para realización de sutura flotante', NULL),
  ('Puntos epiesclerales',
   'se realiza sutura epiescleral de fijación muscular', NULL),
  ('Dexametasona subconjuntival',
   'se coloca dexametasona subconjuntival', NULL),
  ('Dilatación de puntos lagrimales',
   'se procede a dilatar puntos lagrimales superiores e inferiores con dilatador de vía lagrimal', NULL),
  ('Sondaje con sonda de Bowman N.° 2',
   'se procede a permeabilizar vía lagrimal introduciendo sonda de Bowman N.° {numero}', '[{"nombre":"numero","default":"2"}]'::jsonb),
  ('Prueba de permeabilidad con solución salina',
   'se comprueba permeabilidad introduciendo cánula unida a inyectadora cargada con {volumen} cc de solución salina al 0,9 %', '[{"nombre":"volumen","default":"5"}]'::jsonb),
  ('Desepitelización con alcohol absoluto',
   'instilación de alcohol absoluto sobre la lesión corneal y posterior desepitelización con hojilla de bisturí n.° 15', NULL),
  ('Colgajo conjuntival avanzado',
   'se avanza el colgajo sobre la lesión corneal y se fija con vicryl 7-0', NULL),
  ('Colgajo conjuntival bipediculado',
   'se realiza colgajo conjuntival bipediculado', NULL),
  ('Reposición de úvea con espátula de iris',
   'reposición de úvea con espátula de iris', NULL),
  ('Vitrectomía manual con tijera de Vannas',
   'se procede a realizar vitrectomía manual con tijera de Vannas', NULL),
  ('Necrectomía de conjuntiva',
   'se procede a realizar necrectomía de conjuntiva isquémica', NULL),
  ('Pinza de chalazión + incisión subtarsal vertical',
   'se procede a realizar colocación y fijación de pinza de chalazión delimitando el área de lesión, se realiza incisión vertical de {longitud} mm en región subtarsal', '[{"nombre":"longitud","default":"1"}]'::jsonb),
  ('Curetaje con cureta de chalazión',
   'se realiza limpieza del área con cureta de chalazión', NULL)
ON CONFLICT (tecnica) DO NOTHING;

-- =====================================================================
-- Qué técnica se usa en qué procedimiento (578 pares).
-- Derivado de la frecuencia real: `por_defecto` marca las que aparecen en
-- la mitad o más de las notas de ese procedimiento; `orden` es la posición
-- media en el relato, que es cronológico.
-- =====================================================================
INSERT INTO "Procedimiento_Tecnica" (id_procedimiento, id_tecnica, orden, por_defecto)
SELECT p.id, i.id, v.orden, v.por_defecto
FROM (VALUES
  ('Aspiración de masas cristalinianas', 'Anestesia local', 1, TRUE),
  ('Aspiración de masas cristalinianas', 'Anestesia local peribulbar', 2, FALSE),
  ('Aspiración de masas cristalinianas', 'Asepsia y antisepsia del área operatoria', 3, TRUE),
  ('Aspiración de masas cristalinianas', 'Colocación de campos quirúrgicos estériles', 4, TRUE),
  ('Aspiración de masas cristalinianas', 'Tegaderm', 5, TRUE),
  ('Aspiración de masas cristalinianas', 'Blefaróstato', 6, TRUE),
  ('Aspiración de masas cristalinianas', 'Inyección de viscoelástico en cámara anterior', 7, TRUE),
  ('Aspiración de masas cristalinianas', 'Remoción de restos corticales con cánula de Simcoe', 8, TRUE),
  ('Aspiración de masas cristalinianas', 'Remoción de viscoelástico', 9, TRUE),
  ('Aspiración de masas cristalinianas', 'Invaginación de puntos', 10, TRUE),
  ('Aspiración de masas cristalinianas', 'Inyección de miochol', 11, TRUE),
  ('Aspiración de masas cristalinianas', 'Antibiótico subconjuntival', 12, TRUE),
  ('Aspiración de masas cristalinianas', 'Parchado ocular', 13, TRUE),
  ('Colocación de válvula de drenaje', 'Asepsia y antisepsia del área operatoria', 1, TRUE),
  ('Colocación de válvula de drenaje', 'Colocación de campos quirúrgicos estériles', 2, TRUE),
  ('Colocación de válvula de drenaje', 'Tegaderm', 3, TRUE),
  ('Colocación de válvula de drenaje', 'Blefaróstato', 4, TRUE),
  ('Colocación de válvula de drenaje', 'Anestesia subtenon', 5, TRUE),
  ('Colocación de válvula de drenaje', 'Apertura de puertos laterales H3 y H9', 6, TRUE),
  ('Colocación de válvula de drenaje', 'Cauterización de vasos sangrantes', 7, TRUE),
  ('Colocación de válvula de drenaje', 'Puntos epiesclerales', 8, TRUE),
  ('Colocación de válvula de drenaje', 'Posicionamiento de válvula retromuscular a 8 mm del limbo', 9, TRUE),
  ('Colocación de válvula de drenaje', 'Antibiótico tópico', 10, TRUE),
  ('Colocación de válvula de drenaje', 'Asepsia final', 11, TRUE),
  ('Colocación de válvula de drenaje', 'Parchado ocular', 12, TRUE),
  ('Drenaje de chalazión', 'Anestesia local', 1, TRUE),
  ('Drenaje de chalazión', 'Sedación', 2, FALSE),
  ('Drenaje de chalazión', 'Asepsia y antisepsia del área operatoria', 3, TRUE),
  ('Drenaje de chalazión', 'Colocación de campos quirúrgicos estériles', 4, TRUE),
  ('Drenaje de chalazión', 'Pinza de chalazión + incisión subtarsal vertical', 5, TRUE),
  ('Drenaje de chalazión', 'Curetaje con cureta de chalazión', 6, TRUE),
  ('Drenaje de chalazión', 'Dexametasona subconjuntival', 7, TRUE),
  ('Drenaje de chalazión', 'Antibiótico tópico', 8, TRUE),
  ('Drenaje de chalazión', 'Parchado ocular', 9, TRUE),
  ('Explante de LIO', 'Anestesia local', 1, TRUE),
  ('Explante de LIO', 'Anestesia subtenon', 2, FALSE),
  ('Explante de LIO', 'Anestesia local peribulbar', 3, FALSE),
  ('Explante de LIO', 'Asepsia y antisepsia del área operatoria', 4, TRUE),
  ('Explante de LIO', 'Colocación de campos quirúrgicos estériles', 5, TRUE),
  ('Explante de LIO', 'Tegaderm', 6, TRUE),
  ('Explante de LIO', 'Blefaróstato', 7, TRUE),
  ('Explante de LIO', 'Implante de LIO anclado a esclera en H12', 8, FALSE),
  ('Explante de LIO', 'Apertura de puertos laterales H3 y H9', 9, FALSE),
  ('Explante de LIO', 'Aclaramiento con solución Ringer lactato', 10, TRUE),
  ('Explante de LIO', 'Apertura de puerto principal en H11 / H12', 11, FALSE),
  ('Explante de LIO', 'Inyección de viscoelástico en cámara anterior', 12, FALSE),
  ('Explante de LIO', 'Vitrectomía manual con tijera de Vannas', 13, FALSE),
  ('Explante de LIO', 'Remoción de restos corticales con cánula de Simcoe', 14, FALSE),
  ('Explante de LIO', 'Antibiótico subconjuntival', 15, TRUE),
  ('Explante de LIO', 'Antibiótico tópico', 16, TRUE),
  ('Explante de LIO', 'Parchado ocular', 17, TRUE),
  ('Explante de LIO', 'Dexametasona subconjuntival', 18, FALSE),
  ('Exploración quirúrgica', 'Anestesia local', 1, TRUE),
  ('Exploración quirúrgica', 'Anestesia tópica', 2, FALSE),
  ('Exploración quirúrgica', 'Asepsia y antisepsia del área operatoria', 3, TRUE),
  ('Exploración quirúrgica', 'Anestesia local peribulbar', 4, FALSE),
  ('Exploración quirúrgica', 'Colocación de campos quirúrgicos estériles', 5, TRUE),
  ('Exploración quirúrgica', 'Tegaderm', 6, TRUE),
  ('Exploración quirúrgica', 'Blefaróstato', 7, TRUE),
  ('Exploración quirúrgica', 'Anestesia subtenon', 8, FALSE),
  ('Exploración quirúrgica', 'Lavado de superficie con iodopovidona al 10 %', 9, TRUE),
  ('Exploración quirúrgica', 'Aclaramiento con solución Ringer lactato', 10, TRUE),
  ('Exploración quirúrgica', 'Perilimbotomía inferior', 11, FALSE),
  ('Exploración quirúrgica', 'Apertura de puerto principal en H11 / H12', 12, FALSE),
  ('Exploración quirúrgica', 'Necrectomía de conjuntiva', 13, FALSE),
  ('Exploración quirúrgica', 'Inyección de viscoelástico en cámara anterior', 14, FALSE),
  ('Exploración quirúrgica', 'Capsulorrexis circular continua', 15, FALSE),
  ('Exploración quirúrgica', 'Colocación de membrana amniótica', 16, FALSE),
  ('Exploración quirúrgica', 'Remoción de restos corticales con cánula de Simcoe', 17, FALSE),
  ('Exploración quirúrgica', 'Vitrectomía manual con tijera de Vannas', 18, FALSE),
  ('Exploración quirúrgica', 'Puntos epiesclerales', 19, FALSE),
  ('Exploración quirúrgica', 'Antibiótico tópico', 20, TRUE),
  ('Exploración quirúrgica', 'Parchado ocular', 21, TRUE),
  ('Extracción extracapsular + afaquia', 'Anestesia tópica', 1, TRUE),
  ('Extracción extracapsular + afaquia', 'Asepsia y antisepsia del área operatoria', 2, TRUE),
  ('Extracción extracapsular + afaquia', 'Colocación de campos quirúrgicos estériles', 3, TRUE),
  ('Extracción extracapsular + afaquia', 'Tegaderm', 4, TRUE),
  ('Extracción extracapsular + afaquia', 'Blefaróstato', 5, TRUE),
  ('Extracción extracapsular + afaquia', 'Perilimbotomía superior en 180°', 6, TRUE),
  ('Extracción extracapsular + afaquia', 'Cauterización de vasos sangrantes', 7, TRUE),
  ('Extracción extracapsular + afaquia', 'Delineado de surco con cuchillete 15°', 8, TRUE),
  ('Extracción extracapsular + afaquia', 'Profundización con crescent', 9, TRUE),
  ('Extracción extracapsular + afaquia', 'Apertura de puerto principal en H11 / H12', 10, TRUE),
  ('Extracción extracapsular + afaquia', 'Tinción con azul tripán', 11, TRUE),
  ('Extracción extracapsular + afaquia', 'Inyección de viscoelástico en cámara anterior', 12, TRUE),
  ('Extracción extracapsular + afaquia', 'Capsulotomía anterior en abrelatas', 13, TRUE),
  ('Extracción extracapsular + afaquia', 'Extracción de núcleo por presión-contrapresión', 14, TRUE),
  ('Extracción extracapsular + afaquia', 'Remoción de restos corticales con cánula de Simcoe', 15, FALSE),
  ('Extracción extracapsular + afaquia', 'Remoción de viscoelástico', 16, FALSE),
  ('Extracción extracapsular + afaquia', 'Invaginación de puntos', 17, TRUE),
  ('Extracción extracapsular + afaquia', 'Inyección de miochol', 18, TRUE),
  ('Extracción extracapsular + afaquia', 'Antibiótico subconjuntival', 19, TRUE),
  ('Extracción extracapsular + afaquia', 'Antibiótico tópico', 20, TRUE),
  ('Extracción extracapsular + afaquia', 'Parchado ocular', 21, TRUE),
  ('Extracción extracapsular + implante de LIO anclado a esclera', 'Anestesia local', 1, TRUE),
  ('Extracción extracapsular + implante de LIO anclado a esclera', 'Anestesia local peribulbar', 2, FALSE),
  ('Extracción extracapsular + implante de LIO anclado a esclera', 'Asepsia y antisepsia del área operatoria', 3, TRUE),
  ('Extracción extracapsular + implante de LIO anclado a esclera', 'Colocación de campos quirúrgicos estériles', 4, TRUE),
  ('Extracción extracapsular + implante de LIO anclado a esclera', 'Tegaderm', 5, TRUE),
  ('Extracción extracapsular + implante de LIO anclado a esclera', 'Blefaróstato', 6, TRUE),
  ('Extracción extracapsular + implante de LIO anclado a esclera', 'Aclaramiento con solución Ringer lactato', 7, TRUE),
  ('Extracción extracapsular + implante de LIO anclado a esclera', 'Perilimbotomía superior en 180°', 8, TRUE),
  ('Extracción extracapsular + implante de LIO anclado a esclera', 'Cauterización de vasos sangrantes', 9, TRUE),
  ('Extracción extracapsular + implante de LIO anclado a esclera', 'Apertura de puerto principal en H11 / H12', 10, TRUE),
  ('Extracción extracapsular + implante de LIO anclado a esclera', 'Tinción con azul tripán', 11, TRUE),
  ('Extracción extracapsular + implante de LIO anclado a esclera', 'Inyección de viscoelástico en cámara anterior', 12, TRUE),
  ('Extracción extracapsular + implante de LIO anclado a esclera', 'Capsulotomía anterior en abrelatas', 13, TRUE),
  ('Extracción extracapsular + implante de LIO anclado a esclera', 'Remoción de restos corticales con cánula de Simcoe', 14, TRUE),
  ('Extracción extracapsular + implante de LIO anclado a esclera', 'Remoción de viscoelástico', 15, TRUE),
  ('Extracción extracapsular + implante de LIO anclado a esclera', 'Invaginación de puntos', 16, TRUE),
  ('Extracción extracapsular + implante de LIO anclado a esclera', 'Inyección de miochol', 17, TRUE),
  ('Extracción extracapsular + implante de LIO anclado a esclera', 'Antibiótico subconjuntival', 18, TRUE),
  ('Extracción extracapsular + implante de LIO anclado a esclera', 'Parchado ocular', 19, TRUE),
  ('Extracción extracapsular + trabeculectomía + implante de LIO', 'Anestesia local', 1, TRUE),
  ('Extracción extracapsular + trabeculectomía + implante de LIO', 'Anestesia local peribulbar', 2, FALSE),
  ('Extracción extracapsular + trabeculectomía + implante de LIO', 'Asepsia y antisepsia del área operatoria', 3, TRUE),
  ('Extracción extracapsular + trabeculectomía + implante de LIO', 'Colocación de campos quirúrgicos estériles', 4, TRUE),
  ('Extracción extracapsular + trabeculectomía + implante de LIO', 'Tegaderm', 5, TRUE),
  ('Extracción extracapsular + trabeculectomía + implante de LIO', 'Blefaróstato', 6, TRUE),
  ('Extracción extracapsular + trabeculectomía + implante de LIO', 'Aclaramiento con solución Ringer lactato', 7, TRUE),
  ('Extracción extracapsular + trabeculectomía + implante de LIO', 'Lavado de superficie con iodopovidona al 2 %', 8, FALSE),
  ('Extracción extracapsular + trabeculectomía + implante de LIO', 'Perilimbotomía superior en 180°', 9, TRUE),
  ('Extracción extracapsular + trabeculectomía + implante de LIO', 'Cauterización de vasos sangrantes', 10, TRUE),
  ('Extracción extracapsular + trabeculectomía + implante de LIO', 'Divulsión de conjuntiva en base de fórnix', 11, FALSE),
  ('Extracción extracapsular + trabeculectomía + implante de LIO', 'Profundización con crescent', 12, TRUE),
  ('Extracción extracapsular + trabeculectomía + implante de LIO', 'Tenectomía', 13, FALSE),
  ('Extracción extracapsular + trabeculectomía + implante de LIO', 'Apertura de puerto principal en H11 / H12', 14, TRUE),
  ('Extracción extracapsular + trabeculectomía + implante de LIO', 'Tinción con azul tripán', 15, TRUE),
  ('Extracción extracapsular + trabeculectomía + implante de LIO', 'Inyección de viscoelástico en cámara anterior', 16, TRUE),
  ('Extracción extracapsular + trabeculectomía + implante de LIO', 'Capsulotomía anterior en abrelatas', 17, TRUE),
  ('Extracción extracapsular + trabeculectomía + implante de LIO', 'Remoción de restos corticales con cánula de Simcoe', 18, TRUE),
  ('Extracción extracapsular + trabeculectomía + implante de LIO', 'Remoción de viscoelástico', 19, TRUE),
  ('Extracción extracapsular + trabeculectomía + implante de LIO', 'Esclerotomía en charnela cuadrada', 20, TRUE),
  ('Extracción extracapsular + trabeculectomía + implante de LIO', 'Invaginación de puntos', 21, TRUE),
  ('Extracción extracapsular + trabeculectomía + implante de LIO', 'Inyección de miochol', 22, TRUE),
  ('Extracción extracapsular + trabeculectomía + implante de LIO', 'Mitomicina C tópica durante 3 minutos', 23, TRUE),
  ('Extracción extracapsular + trabeculectomía + implante de LIO', 'Extracción de núcleo por presión-contrapresión', 24, FALSE),
  ('Extracción extracapsular + trabeculectomía + implante de LIO', 'Apertura de puertos laterales H3 y H9', 25, TRUE),
  ('Extracción extracapsular + trabeculectomía + implante de LIO', 'Iridotomía con pinza punch de Kelly', 26, TRUE),
  ('Extracción extracapsular + trabeculectomía + implante de LIO', 'Antibiótico tópico', 27, TRUE),
  ('Extracción extracapsular + trabeculectomía + implante de LIO', 'Parchado ocular', 28, TRUE),
  ('Extracción extracapsular + trabeculectomía + implante de LIO', 'Antibiótico subconjuntival', 29, TRUE),
  ('Extracción extracapsular + vitrectomía anterior', 'Anestesia tópica', 1, TRUE),
  ('Extracción extracapsular + vitrectomía anterior', 'Asepsia y antisepsia del área operatoria', 2, TRUE),
  ('Extracción extracapsular + vitrectomía anterior', 'Colocación de campos quirúrgicos estériles', 3, TRUE),
  ('Extracción extracapsular + vitrectomía anterior', 'Tegaderm', 4, TRUE),
  ('Extracción extracapsular + vitrectomía anterior', 'Blefaróstato', 5, TRUE),
  ('Extracción extracapsular + vitrectomía anterior', 'Perilimbotomía superior en 180°', 6, TRUE),
  ('Extracción extracapsular + vitrectomía anterior', 'Cauterización de vasos sangrantes', 7, TRUE),
  ('Extracción extracapsular + vitrectomía anterior', 'Delineado de surco con cuchillete 15°', 8, TRUE),
  ('Extracción extracapsular + vitrectomía anterior', 'Profundización con crescent', 9, TRUE),
  ('Extracción extracapsular + vitrectomía anterior', 'Apertura de puerto principal en H11 / H12', 10, TRUE),
  ('Extracción extracapsular + vitrectomía anterior', 'Tinción con azul tripán', 11, TRUE),
  ('Extracción extracapsular + vitrectomía anterior', 'Inyección de viscoelástico en cámara anterior', 12, TRUE),
  ('Extracción extracapsular + vitrectomía anterior', 'Capsulotomía anterior en abrelatas', 13, TRUE),
  ('Extracción extracapsular + vitrectomía anterior', 'Extracción de núcleo por presión-contrapresión', 14, TRUE),
  ('Extracción extracapsular + vitrectomía anterior', 'Invaginación de puntos', 15, TRUE),
  ('Extracción extracapsular + vitrectomía anterior', 'Inyección de miochol', 16, TRUE),
  ('Extracción extracapsular + vitrectomía anterior', 'Antibiótico subconjuntival', 17, TRUE),
  ('Extracción extracapsular + vitrectomía anterior', 'Antibiótico tópico', 18, TRUE),
  ('Extracción extracapsular + vitrectomía anterior', 'Parchado ocular', 19, TRUE),
  ('Extracción extracapsular de catarata + implante de LIO', 'Anestesia local', 1, TRUE),
  ('Extracción extracapsular de catarata + implante de LIO', 'Anestesia tópica', 2, FALSE),
  ('Extracción extracapsular de catarata + implante de LIO', 'Anestesia local peribulbar', 3, FALSE),
  ('Extracción extracapsular de catarata + implante de LIO', 'Anestesia subtenon', 4, FALSE),
  ('Extracción extracapsular de catarata + implante de LIO', 'Asepsia y antisepsia del área operatoria', 5, TRUE),
  ('Extracción extracapsular de catarata + implante de LIO', 'Colocación de campos quirúrgicos estériles', 6, TRUE),
  ('Extracción extracapsular de catarata + implante de LIO', 'Tegaderm', 7, TRUE),
  ('Extracción extracapsular de catarata + implante de LIO', 'Blefaróstato', 8, TRUE),
  ('Extracción extracapsular de catarata + implante de LIO', 'Aclaramiento con solución Ringer lactato', 9, TRUE),
  ('Extracción extracapsular de catarata + implante de LIO', 'Perilimbotomía superior en 180°', 10, TRUE),
  ('Extracción extracapsular de catarata + implante de LIO', 'Cauterización de vasos sangrantes', 11, TRUE),
  ('Extracción extracapsular de catarata + implante de LIO', 'Delineado de surco con cuchillete 15°', 12, TRUE),
  ('Extracción extracapsular de catarata + implante de LIO', 'Profundización con crescent', 13, TRUE),
  ('Extracción extracapsular de catarata + implante de LIO', 'Apertura de puerto principal en H11 / H12', 14, TRUE),
  ('Extracción extracapsular de catarata + implante de LIO', 'Capsulorrexis circular continua', 15, FALSE),
  ('Extracción extracapsular de catarata + implante de LIO', 'Tinción con azul tripán', 16, TRUE),
  ('Extracción extracapsular de catarata + implante de LIO', 'Dilatación de puntos lagrimales', 17, FALSE),
  ('Extracción extracapsular de catarata + implante de LIO', 'Hidrodisección', 18, FALSE),
  ('Extracción extracapsular de catarata + implante de LIO', 'Inyección de viscoelástico en cámara anterior', 19, TRUE),
  ('Extracción extracapsular de catarata + implante de LIO', 'Capsulotomía anterior en abrelatas', 20, TRUE),
  ('Extracción extracapsular de catarata + implante de LIO', 'Extracción de núcleo por presión-contrapresión', 21, TRUE),
  ('Extracción extracapsular de catarata + implante de LIO', 'Implante de LIO en saco capsular', 22, TRUE),
  ('Extracción extracapsular de catarata + implante de LIO', 'Remoción de restos corticales con cánula de Simcoe', 23, TRUE),
  ('Extracción extracapsular de catarata + implante de LIO', 'Remoción de viscoelástico', 24, TRUE),
  ('Extracción extracapsular de catarata + implante de LIO', 'Invaginación de puntos', 25, TRUE),
  ('Extracción extracapsular de catarata + implante de LIO', 'Inyección de miochol', 26, TRUE),
  ('Extracción extracapsular de catarata + implante de LIO', 'Antibiótico subconjuntival', 27, TRUE),
  ('Extracción extracapsular de catarata + implante de LIO', 'Dexametasona subconjuntival', 28, FALSE),
  ('Extracción extracapsular de catarata + implante de LIO', 'Antibiótico tópico', 29, TRUE),
  ('Extracción extracapsular de catarata + implante de LIO', 'Parchado ocular', 30, TRUE),
  ('Exéresis de granuloma', 'Anestesia local', 1, TRUE),
  ('Exéresis de granuloma', 'Asepsia y antisepsia del área operatoria', 2, TRUE),
  ('Exéresis de granuloma', 'Colocación de campos quirúrgicos estériles', 3, TRUE),
  ('Exéresis de granuloma', 'Blefaróstato', 4, TRUE),
  ('Exéresis de granuloma', 'Lavado de superficie con iodopovidona al 10 %', 5, TRUE),
  ('Exéresis de granuloma', 'Infiltración de lidocaína subconjuntival', 6, TRUE),
  ('Exéresis de granuloma', 'Tenectomía', 7, TRUE),
  ('Exéresis de granuloma', 'Verificación de hemostasia', 8, TRUE),
  ('Exéresis de granuloma', 'Antibiótico tópico', 9, TRUE),
  ('Exéresis de granuloma', 'Parchado ocular', 10, TRUE),
  ('Exéresis de pterigión', 'Anestesia local', 1, TRUE),
  ('Exéresis de pterigión', 'Asepsia y antisepsia del área operatoria', 2, TRUE),
  ('Exéresis de pterigión', 'Colocación de campos quirúrgicos estériles', 3, TRUE),
  ('Exéresis de pterigión', 'Blefaróstato', 4, TRUE),
  ('Exéresis de pterigión', 'Lavado de superficie con iodopovidona al 10 %', 5, TRUE),
  ('Exéresis de pterigión', 'Infiltración de lidocaína subconjuntival', 6, TRUE),
  ('Exéresis de pterigión', 'Queratoplastia de cabeza de pterigión', 7, TRUE),
  ('Exéresis de pterigión', 'Autoinjerto conjuntival', 8, TRUE),
  ('Exéresis de pterigión', 'Tenectomía', 9, TRUE),
  ('Exéresis de pterigión', 'Mitomicina C tópica durante 3 minutos', 10, FALSE),
  ('Exéresis de pterigión', 'Aclaramiento con solución Ringer lactato', 11, FALSE),
  ('Exéresis de pterigión', 'Colocación de membrana amniótica', 12, FALSE),
  ('Exéresis de pterigión', 'Verificación de hemostasia', 13, TRUE),
  ('Exéresis de pterigión', 'Antibiótico tópico', 14, TRUE),
  ('Exéresis de pterigión', 'Parchado ocular', 15, TRUE),
  ('Exéresis de quiste sebáceo palpebral', 'Anestesia general', 1, TRUE),
  ('Exéresis de quiste sebáceo palpebral', 'Sedación', 2, FALSE),
  ('Exéresis de quiste sebáceo palpebral', 'Asepsia y antisepsia del área operatoria', 3, TRUE),
  ('Exéresis de quiste sebáceo palpebral', 'Colocación de campos quirúrgicos estériles', 4, TRUE),
  ('Exéresis de quiste sebáceo palpebral', 'Cauterización de vasos sangrantes', 5, TRUE),
  ('Exéresis de quiste sebáceo palpebral', 'Asepsia final', 6, TRUE),
  ('Exéresis de quiste sebáceo palpebral', 'Antibiótico tópico', 7, TRUE),
  ('Exéresis de quiste sebáceo palpebral', 'Parchado ocular', 8, TRUE),
  ('Facoemulsificación + implante de LIO', 'Anestesia tópica', 1, TRUE),
  ('Facoemulsificación + implante de LIO', 'Asepsia y antisepsia del área operatoria', 2, TRUE),
  ('Facoemulsificación + implante de LIO', 'Colocación de campos quirúrgicos estériles', 3, TRUE),
  ('Facoemulsificación + implante de LIO', 'Tegaderm', 4, TRUE),
  ('Facoemulsificación + implante de LIO', 'Blefaróstato', 5, TRUE),
  ('Facoemulsificación + implante de LIO', 'Apertura de puertos laterales H3 y H9', 6, TRUE),
  ('Facoemulsificación + implante de LIO', 'Tinción con azul tripán', 7, TRUE),
  ('Facoemulsificación + implante de LIO', 'Inyección de viscoelástico en cámara anterior', 8, TRUE),
  ('Facoemulsificación + implante de LIO', 'Apertura de puerto principal en H11 / H12', 9, TRUE),
  ('Facoemulsificación + implante de LIO', 'Capsulorrexis circular continua', 10, TRUE),
  ('Facoemulsificación + implante de LIO', 'Hidrodisección', 11, TRUE),
  ('Facoemulsificación + implante de LIO', 'Facoemulsificación con técnica *stop and chop*', 12, TRUE),
  ('Facoemulsificación + implante de LIO', 'Remoción de viscoelástico', 13, TRUE),
  ('Facoemulsificación + implante de LIO', 'Hidratación de puertos laterales', 14, TRUE),
  ('Facoemulsificación + implante de LIO', 'Inyección de miochol', 15, TRUE),
  ('Facoemulsificación + implante de LIO', 'Antibiótico subconjuntival', 16, TRUE),
  ('Facoemulsificación + implante de LIO', 'Antibiótico tópico', 17, TRUE),
  ('Facoemulsificación + implante de LIO', 'Parchado ocular', 18, TRUE),
  ('Implante secundario de LIO anclado a esclera', 'Anestesia local peribulbar', 1, TRUE),
  ('Implante secundario de LIO anclado a esclera', 'Asepsia y antisepsia del área operatoria', 2, TRUE),
  ('Implante secundario de LIO anclado a esclera', 'Colocación de campos quirúrgicos estériles', 3, TRUE),
  ('Implante secundario de LIO anclado a esclera', 'Tegaderm', 4, TRUE),
  ('Implante secundario de LIO anclado a esclera', 'Blefaróstato', 5, TRUE),
  ('Implante secundario de LIO anclado a esclera', 'Apertura de puerto principal en H11 / H12', 6, TRUE),
  ('Implante secundario de LIO anclado a esclera', 'Inyección de viscoelástico en cámara anterior', 7, TRUE),
  ('Implante secundario de LIO anclado a esclera', 'Invaginación de puntos', 8, TRUE),
  ('Implante secundario de LIO anclado a esclera', 'Dexametasona subconjuntival', 9, TRUE),
  ('Implante secundario de LIO anclado a esclera', 'Antibiótico tópico', 10, TRUE),
  ('Implante secundario de LIO anclado a esclera', 'Parchado ocular', 11, TRUE),
  ('Iridectomía', 'Anestesia local', 1, TRUE),
  ('Iridectomía', 'Asepsia y antisepsia del área operatoria', 2, TRUE),
  ('Iridectomía', 'Colocación de campos quirúrgicos estériles', 3, TRUE),
  ('Iridectomía', 'Blefaróstato', 4, TRUE),
  ('Iridectomía', 'Perilimbotomía superior en 180°', 5, TRUE),
  ('Iridectomía', 'Delineado de surco con cuchillete 15°', 6, TRUE),
  ('Iridectomía', 'Profundización con crescent', 7, TRUE),
  ('Iridectomía', 'Apertura de puerto principal en H11 / H12', 8, TRUE),
  ('Iridectomía', 'Inyección de viscoelástico en cámara anterior', 9, TRUE),
  ('Iridectomía', 'Iridectomía en H12', 10, TRUE),
  ('Iridectomía', 'Remoción de viscoelástico', 11, TRUE),
  ('Iridectomía', 'Antibiótico subconjuntival', 12, TRUE),
  ('Iridectomía', 'Parchado ocular', 13, TRUE),
  ('Miectomía de oblicuo inferior', 'Anestesia general', 1, TRUE),
  ('Miectomía de oblicuo inferior', 'Asepsia y antisepsia del área operatoria', 2, TRUE),
  ('Miectomía de oblicuo inferior', 'Colocación de campos quirúrgicos estériles', 3, TRUE),
  ('Miectomía de oblicuo inferior', 'Tegaderm', 4, TRUE),
  ('Miectomía de oblicuo inferior', 'Blefaróstato', 5, TRUE),
  ('Miectomía de oblicuo inferior', 'Aclaramiento con solución Ringer lactato', 6, TRUE),
  ('Miectomía de oblicuo inferior', 'Puntos epiesclerales', 7, TRUE),
  ('Miectomía de oblicuo inferior', 'Referencia de conjuntiva con seda 4-0', 8, FALSE),
  ('Miectomía de oblicuo inferior', 'Incisiones relajantes', 9, FALSE),
  ('Miectomía de oblicuo inferior', 'Desinserción muscular con tijera Westcott', 10, FALSE),
  ('Miectomía de oblicuo inferior', 'Cauterización de vasos sangrantes', 11, TRUE),
  ('Miectomía de oblicuo inferior', 'Verificación de hemostasia', 12, TRUE),
  ('Miectomía de oblicuo inferior', 'Dexametasona subconjuntival', 13, TRUE),
  ('Miectomía de oblicuo inferior', 'Parchado ocular', 14, FALSE),
  ('Miectomía de oblicuo inferior', 'Antibiótico tópico', 15, TRUE),
  ('Mioescleropexia retroecuatorial', 'Anestesia general', 1, TRUE),
  ('Mioescleropexia retroecuatorial', 'Asepsia y antisepsia del área operatoria', 2, TRUE),
  ('Mioescleropexia retroecuatorial', 'Colocación de campos quirúrgicos estériles', 3, TRUE),
  ('Mioescleropexia retroecuatorial', 'Tegaderm', 4, TRUE),
  ('Mioescleropexia retroecuatorial', 'Blefaróstato', 5, TRUE),
  ('Mioescleropexia retroecuatorial', 'Lavado de superficie con iodopovidona al 10 %', 6, TRUE),
  ('Mioescleropexia retroecuatorial', 'Fijación del globo ocular en H12 y H6', 7, TRUE),
  ('Mioescleropexia retroecuatorial', 'Puntos epiesclerales', 8, TRUE),
  ('Mioescleropexia retroecuatorial', 'Antibiótico tópico', 9, TRUE),
  ('Needling + mitomicina C', 'Asepsia y antisepsia del área operatoria', 1, TRUE),
  ('Needling + mitomicina C', 'Colocación de campos quirúrgicos estériles', 2, TRUE),
  ('Needling + mitomicina C', 'Tegaderm', 3, TRUE),
  ('Needling + mitomicina C', 'Blefaróstato', 4, TRUE),
  ('Needling + mitomicina C', 'Aclaramiento con solución Ringer lactato', 5, TRUE),
  ('Needling + mitomicina C', 'Anestesia subtenon', 6, TRUE),
  ('Needling + mitomicina C', 'Reposición de úvea con espátula de iris', 7, TRUE),
  ('Needling + mitomicina C', 'Mitomicina C tópica durante 3 minutos', 8, TRUE),
  ('Needling + mitomicina C', 'Needling con aguja de insulina', 9, TRUE),
  ('Needling + mitomicina C', 'Antibiótico tópico', 10, TRUE),
  ('Needling + mitomicina C', 'Parchado ocular', 11, TRUE),
  ('Puntoplastia', 'Anestesia local', 1, TRUE),
  ('Puntoplastia', 'Asepsia y antisepsia del área operatoria', 2, TRUE),
  ('Puntoplastia', 'Colocación de campos quirúrgicos estériles', 3, TRUE),
  ('Puntoplastia', 'Dilatación de puntos lagrimales', 4, TRUE),
  ('Puntoplastia', 'Sondaje con sonda de Bowman N.° 2', 5, TRUE),
  ('Puntoplastia', 'Prueba de permeabilidad con solución salina', 6, TRUE),
  ('Puntoplastia', 'Asepsia final', 7, TRUE),
  ('Rafia de herida palpebral', 'Anestesia local', 1, TRUE),
  ('Rafia de herida palpebral', 'Asepsia y antisepsia del área operatoria', 2, TRUE),
  ('Rafia de herida palpebral', 'Verificación de hemostasia', 3, TRUE),
  ('Recanalización de vías lagrimales', 'Anestesia local', 1, TRUE),
  ('Recanalización de vías lagrimales', 'Asepsia y antisepsia del área operatoria', 2, TRUE),
  ('Recanalización de vías lagrimales', 'Colocación de campos quirúrgicos estériles', 3, TRUE),
  ('Recanalización de vías lagrimales', 'Blefaróstato', 4, TRUE),
  ('Recanalización de vías lagrimales', 'Lavado de superficie con iodopovidona al 10 %', 5, TRUE),
  ('Recanalización de vías lagrimales', 'Dilatación de puntos lagrimales', 6, TRUE),
  ('Recanalización de vías lagrimales', 'Sondaje con sonda de Bowman N.° 2', 7, TRUE),
  ('Recanalización de vías lagrimales', 'Prueba de permeabilidad con solución salina', 8, TRUE),
  ('Recanalización de vías lagrimales', 'Antibiótico tópico', 9, TRUE),
  ('Recubrimiento conjuntival', 'Anestesia tópica', 1, TRUE),
  ('Recubrimiento conjuntival', 'Anestesia general', 2, FALSE),
  ('Recubrimiento conjuntival', 'Asepsia y antisepsia del área operatoria', 3, TRUE),
  ('Recubrimiento conjuntival', 'Colocación de campos quirúrgicos estériles', 4, TRUE),
  ('Recubrimiento conjuntival', 'Tegaderm', 5, TRUE),
  ('Recubrimiento conjuntival', 'Blefaróstato', 6, TRUE),
  ('Recubrimiento conjuntival', 'Lavado de superficie con iodopovidona al 10 %', 7, TRUE),
  ('Recubrimiento conjuntival', 'Aclaramiento con solución Ringer lactato', 8, TRUE),
  ('Recubrimiento conjuntival', 'Anestesia subtenon', 9, FALSE),
  ('Recubrimiento conjuntival', 'Desepitelización con alcohol absoluto', 10, TRUE),
  ('Recubrimiento conjuntival', 'Colgajo conjuntival bipediculado', 11, TRUE),
  ('Recubrimiento conjuntival', 'Colgajo conjuntival avanzado', 12, TRUE),
  ('Recubrimiento conjuntival', 'Antibiótico subconjuntival', 13, TRUE),
  ('Recubrimiento conjuntival', 'Parchado ocular', 14, TRUE),
  ('Recubrimiento conjuntival bipediculado', 'Anestesia tópica', 1, TRUE),
  ('Recubrimiento conjuntival bipediculado', 'Asepsia y antisepsia del área operatoria', 2, TRUE),
  ('Recubrimiento conjuntival bipediculado', 'Colocación de campos quirúrgicos estériles', 3, TRUE),
  ('Recubrimiento conjuntival bipediculado', 'Tegaderm', 4, TRUE),
  ('Recubrimiento conjuntival bipediculado', 'Lavado de superficie con iodopovidona al 10 %', 5, TRUE),
  ('Recubrimiento conjuntival bipediculado', 'Aclaramiento con solución Ringer lactato', 6, TRUE),
  ('Recubrimiento conjuntival bipediculado', 'Anestesia subtenon', 7, FALSE),
  ('Recubrimiento conjuntival bipediculado', 'Desepitelización con alcohol absoluto', 8, TRUE),
  ('Recubrimiento conjuntival bipediculado', 'Colgajo conjuntival avanzado', 9, TRUE),
  ('Recubrimiento conjuntival bipediculado', 'Parchado ocular', 10, TRUE),
  ('Reposición de válvula de drenaje', 'Asepsia y antisepsia del área operatoria', 1, TRUE),
  ('Reposición de válvula de drenaje', 'Colocación de campos quirúrgicos estériles', 2, TRUE),
  ('Reposición de válvula de drenaje', 'Tegaderm', 3, TRUE),
  ('Reposición de válvula de drenaje', 'Blefaróstato', 4, TRUE),
  ('Reposición de válvula de drenaje', 'Anestesia tópica', 5, TRUE),
  ('Reposición de válvula de drenaje', 'Apertura de puertos laterales H3 y H9', 6, TRUE),
  ('Reposición de válvula de drenaje', 'Antibiótico tópico', 7, TRUE),
  ('Reposición de válvula de drenaje', 'Asepsia final', 8, TRUE),
  ('Reposición pupilar + aspiración de masas cristalinianas', 'Anestesia local', 1, TRUE),
  ('Reposición pupilar + aspiración de masas cristalinianas', 'Anestesia local peribulbar', 2, FALSE),
  ('Reposición pupilar + aspiración de masas cristalinianas', 'Asepsia y antisepsia del área operatoria', 3, TRUE),
  ('Reposición pupilar + aspiración de masas cristalinianas', 'Colocación de campos quirúrgicos estériles', 4, TRUE),
  ('Reposición pupilar + aspiración de masas cristalinianas', 'Tegaderm', 5, TRUE),
  ('Reposición pupilar + aspiración de masas cristalinianas', 'Blefaróstato', 6, TRUE),
  ('Reposición pupilar + aspiración de masas cristalinianas', 'Inyección de viscoelástico en cámara anterior', 7, TRUE),
  ('Reposición pupilar + aspiración de masas cristalinianas', 'Remoción de restos corticales con cánula de Simcoe', 8, TRUE),
  ('Reposición pupilar + aspiración de masas cristalinianas', 'Remoción de viscoelástico', 9, TRUE),
  ('Reposición pupilar + aspiración de masas cristalinianas', 'Invaginación de puntos', 10, TRUE),
  ('Reposición pupilar + aspiración de masas cristalinianas', 'Inyección de miochol', 11, TRUE),
  ('Reposición pupilar + aspiración de masas cristalinianas', 'Antibiótico subconjuntival', 12, TRUE),
  ('Reposición pupilar + aspiración de masas cristalinianas', 'Parchado ocular', 13, TRUE),
  ('Reposición uveal', 'Anestesia local', 1, TRUE),
  ('Reposición uveal', 'Asepsia y antisepsia del área operatoria', 2, TRUE),
  ('Reposición uveal', 'Colocación de campos quirúrgicos estériles', 3, TRUE),
  ('Reposición uveal', 'Blefaróstato', 4, TRUE),
  ('Reposición uveal', 'Aclaramiento con solución Ringer lactato', 5, TRUE),
  ('Reposición uveal', 'Reposición de úvea con espátula de iris', 6, TRUE),
  ('Reposición uveal', 'Invaginación de puntos', 7, TRUE),
  ('Reposición uveal', 'Antibiótico tópico', 8, TRUE),
  ('Reposición uveal', 'Parchado ocular', 9, TRUE),
  ('Reposición uveal + rafia corneoescleral', 'Anestesia local', 1, TRUE),
  ('Reposición uveal + rafia corneoescleral', 'Anestesia local peribulbar', 2, FALSE),
  ('Reposición uveal + rafia corneoescleral', 'Asepsia y antisepsia del área operatoria', 3, TRUE),
  ('Reposición uveal + rafia corneoescleral', 'Colocación de campos quirúrgicos estériles', 4, TRUE),
  ('Reposición uveal + rafia corneoescleral', 'Tegaderm', 5, TRUE),
  ('Reposición uveal + rafia corneoescleral', 'Blefaróstato', 6, TRUE),
  ('Reposición uveal + rafia corneoescleral', 'Antibiótico tópico', 7, TRUE),
  ('Reposición uveal + rafia corneoescleral', 'Profundización con crescent', 8, TRUE),
  ('Reposición uveal + rafia corneoescleral', 'Inyección de viscoelástico en cámara anterior', 9, TRUE),
  ('Reposición uveal + rafia corneoescleral', 'Reposición de úvea con espátula de iris', 10, TRUE),
  ('Reposición uveal + rafia corneoescleral', 'Invaginación de puntos', 11, TRUE),
  ('Reposición uveal + rafia corneoescleral', 'Antibiótico subconjuntival', 12, TRUE),
  ('Reposición uveal + rafia corneoescleral', 'Parchado ocular', 13, TRUE),
  ('Resección del recto lateral', 'Anestesia general', 1, TRUE),
  ('Resección del recto lateral', 'Asepsia y antisepsia del área operatoria', 2, TRUE),
  ('Resección del recto lateral', 'Colocación de campos quirúrgicos estériles', 3, TRUE),
  ('Resección del recto lateral', 'Tegaderm', 4, TRUE),
  ('Resección del recto lateral', 'Blefaróstato', 5, TRUE),
  ('Resección del recto lateral', 'Referencia de conjuntiva con seda 4-0', 6, TRUE),
  ('Resección del recto lateral', 'Incisiones relajantes', 7, TRUE),
  ('Resección del recto lateral', 'Puntos epiesclerales', 8, TRUE),
  ('Resección del recto lateral', 'Desinserción muscular con tijera Westcott', 9, TRUE),
  ('Resección del recto lateral', 'Dexametasona subconjuntival', 10, TRUE),
  ('Resección del recto lateral', 'Antibiótico tópico', 11, TRUE),
  ('Resección del recto lateral', 'Parchado ocular', 12, TRUE),
  ('Resección del recto medio', 'Anestesia general', 1, TRUE),
  ('Resección del recto medio', 'Asepsia y antisepsia del área operatoria', 2, TRUE),
  ('Resección del recto medio', 'Colocación de campos quirúrgicos estériles', 3, TRUE),
  ('Resección del recto medio', 'Tegaderm', 4, TRUE),
  ('Resección del recto medio', 'Blefaróstato', 5, TRUE),
  ('Resección del recto medio', 'Referencia de conjuntiva con seda 4-0', 6, TRUE),
  ('Resección del recto medio', 'Incisiones relajantes', 7, TRUE),
  ('Resección del recto medio', 'Puntos epiesclerales', 8, TRUE),
  ('Resección del recto medio', 'Desinserción muscular con tijera Westcott', 9, TRUE),
  ('Resección del recto medio', 'Dexametasona subconjuntival', 10, TRUE),
  ('Resección del recto medio', 'Antibiótico tópico', 11, TRUE),
  ('Resección del recto medio', 'Parchado ocular', 12, TRUE),
  ('Resección y avance del recto medio', 'Anestesia general', 1, TRUE),
  ('Resección y avance del recto medio', 'Asepsia y antisepsia del área operatoria', 2, TRUE),
  ('Resección y avance del recto medio', 'Colocación de campos quirúrgicos estériles', 3, TRUE),
  ('Resección y avance del recto medio', 'Tegaderm', 4, TRUE),
  ('Resección y avance del recto medio', 'Blefaróstato', 5, TRUE),
  ('Resección y avance del recto medio', 'Referencia de conjuntiva con seda 4-0', 6, TRUE),
  ('Resección y avance del recto medio', 'Incisiones relajantes', 7, TRUE),
  ('Resección y avance del recto medio', 'Puntos epiesclerales', 8, TRUE),
  ('Resección y avance del recto medio', 'Desinserción muscular con tijera Westcott', 9, TRUE),
  ('Resección y avance del recto medio', 'Dexametasona subconjuntival', 10, TRUE),
  ('Resección y avance del recto medio', 'Antibiótico tópico', 11, TRUE),
  ('Resección y avance del recto medio', 'Parchado ocular', 12, TRUE),
  ('Retiro de material médico quirúrgico', 'Anestesia local', 1, TRUE),
  ('Retiro de material médico quirúrgico', 'Sedación', 2, FALSE),
  ('Retiro de material médico quirúrgico', 'Anestesia local peribulbar', 3, FALSE),
  ('Retiro de material médico quirúrgico', 'Asepsia y antisepsia del área operatoria', 4, TRUE),
  ('Retiro de material médico quirúrgico', 'Colocación de campos quirúrgicos estériles', 5, TRUE),
  ('Retiro de material médico quirúrgico', 'Antibiótico tópico', 6, FALSE),
  ('Retiro de material médico quirúrgico', 'Blefaróstato', 7, TRUE),
  ('Retiro de material médico quirúrgico', 'Tegaderm', 8, TRUE),
  ('Retroceso + resección del recto medio', 'Anestesia general', 1, TRUE),
  ('Retroceso + resección del recto medio', 'Asepsia y antisepsia del área operatoria', 2, TRUE),
  ('Retroceso + resección del recto medio', 'Colocación de campos quirúrgicos estériles', 3, TRUE),
  ('Retroceso + resección del recto medio', 'Tegaderm', 4, TRUE),
  ('Retroceso + resección del recto medio', 'Blefaróstato', 5, TRUE),
  ('Retroceso + resección del recto medio', 'Lavado de superficie con iodopovidona al 10 %', 6, TRUE),
  ('Retroceso + resección del recto medio', 'Fijación del globo ocular en H12 y H6', 7, TRUE),
  ('Retroceso + resección del recto medio', 'Bolsillo conjuntival', 8, TRUE),
  ('Retroceso + resección del recto medio', 'Incisiones relajantes', 9, TRUE),
  ('Retroceso + resección del recto medio', 'Desinserción muscular con tijera Westcott', 10, TRUE),
  ('Retroceso + resección del recto medio', 'Sutura flotante', 11, TRUE),
  ('Retroceso + resección del recto medio', 'Puntos epiesclerales', 12, TRUE),
  ('Retroceso + resección del recto medio', 'Dexametasona subconjuntival', 13, TRUE),
  ('Retroceso + resección del recto medio', 'Antibiótico tópico', 14, TRUE),
  ('Retroceso + resección del recto medio', 'Parchado ocular', 15, TRUE),
  ('Retroceso bilateral de rectos medios + miectomía bilateral de oblicuos inferiores', 'Anestesia general', 1, TRUE),
  ('Retroceso bilateral de rectos medios + miectomía bilateral de oblicuos inferiores', 'Asepsia y antisepsia del área operatoria', 2, TRUE),
  ('Retroceso bilateral de rectos medios + miectomía bilateral de oblicuos inferiores', 'Colocación de campos quirúrgicos estériles', 3, TRUE),
  ('Retroceso bilateral de rectos medios + miectomía bilateral de oblicuos inferiores', 'Tegaderm', 4, TRUE),
  ('Retroceso bilateral de rectos medios + miectomía bilateral de oblicuos inferiores', 'Blefaróstato', 5, TRUE),
  ('Retroceso bilateral de rectos medios + miectomía bilateral de oblicuos inferiores', 'Referencia de conjuntiva con seda 4-0', 6, TRUE),
  ('Retroceso bilateral de rectos medios + miectomía bilateral de oblicuos inferiores', 'Incisiones relajantes', 7, TRUE),
  ('Retroceso bilateral de rectos medios + miectomía bilateral de oblicuos inferiores', 'Puntos epiesclerales', 8, TRUE),
  ('Retroceso bilateral de rectos medios + miectomía bilateral de oblicuos inferiores', 'Cauterización de vasos sangrantes', 9, TRUE),
  ('Retroceso bilateral de rectos medios + miectomía bilateral de oblicuos inferiores', 'Dexametasona subconjuntival', 10, TRUE),
  ('Retroceso bilateral de rectos medios + miectomía bilateral de oblicuos inferiores', 'Antibiótico tópico', 11, TRUE),
  ('Retroceso bilateral de rectos medios + miectomía bilateral de oblicuos inferiores', 'Parchado ocular', 12, TRUE),
  ('Retroceso del músculo oblicuo inferior', 'Anestesia general', 1, TRUE),
  ('Retroceso del músculo oblicuo inferior', 'Asepsia y antisepsia del área operatoria', 2, TRUE),
  ('Retroceso del músculo oblicuo inferior', 'Colocación de campos quirúrgicos estériles', 3, TRUE),
  ('Retroceso del músculo oblicuo inferior', 'Tegaderm', 4, TRUE),
  ('Retroceso del músculo oblicuo inferior', 'Blefaróstato', 5, TRUE),
  ('Retroceso del músculo oblicuo inferior', 'Lavado de superficie con iodopovidona al 10 %', 6, TRUE),
  ('Retroceso del músculo oblicuo inferior', 'Fijación del globo ocular en H12 y H6', 7, TRUE),
  ('Retroceso del músculo oblicuo inferior', 'Bolsillo conjuntival', 8, TRUE),
  ('Retroceso del músculo oblicuo inferior', 'Incisiones relajantes', 9, TRUE),
  ('Retroceso del músculo oblicuo inferior', 'Desinserción muscular con tijera Westcott', 10, TRUE),
  ('Retroceso del músculo oblicuo inferior', 'Sutura flotante', 11, TRUE),
  ('Retroceso del músculo oblicuo inferior', 'Puntos epiesclerales', 12, TRUE),
  ('Retroceso del músculo oblicuo inferior', 'Dexametasona subconjuntival', 13, TRUE),
  ('Retroceso del músculo oblicuo inferior', 'Antibiótico tópico', 14, TRUE),
  ('Retroceso del músculo oblicuo inferior', 'Parchado ocular', 15, TRUE),
  ('Retroceso del recto lateral', 'Anestesia general', 1, TRUE),
  ('Retroceso del recto lateral', 'Asepsia y antisepsia del área operatoria', 2, TRUE),
  ('Retroceso del recto lateral', 'Colocación de campos quirúrgicos estériles', 3, TRUE),
  ('Retroceso del recto lateral', 'Tegaderm', 4, TRUE),
  ('Retroceso del recto lateral', 'Blefaróstato', 5, TRUE),
  ('Retroceso del recto lateral', 'Lavado de superficie con iodopovidona al 10 %', 6, TRUE),
  ('Retroceso del recto lateral', 'Fijación del globo ocular en H12 y H6', 7, TRUE),
  ('Retroceso del recto lateral', 'Bolsillo conjuntival', 8, TRUE),
  ('Retroceso del recto lateral', 'Incisiones relajantes', 9, TRUE),
  ('Retroceso del recto lateral', 'Desinserción muscular con tijera Westcott', 10, TRUE),
  ('Retroceso del recto lateral', 'Sutura flotante', 11, TRUE),
  ('Retroceso del recto lateral', 'Puntos epiesclerales', 12, TRUE),
  ('Retroceso del recto lateral', 'Dexametasona subconjuntival', 13, TRUE),
  ('Retroceso del recto lateral', 'Antibiótico tópico', 14, TRUE),
  ('Retroceso del recto lateral', 'Parchado ocular', 15, TRUE),
  ('Retroceso del recto medio', 'Anestesia local', 1, FALSE),
  ('Retroceso del recto medio', 'Anestesia general', 2, TRUE),
  ('Retroceso del recto medio', 'Asepsia y antisepsia del área operatoria', 3, TRUE),
  ('Retroceso del recto medio', 'Anestesia local peribulbar', 4, FALSE),
  ('Retroceso del recto medio', 'Colocación de campos quirúrgicos estériles', 5, TRUE),
  ('Retroceso del recto medio', 'Tegaderm', 6, TRUE),
  ('Retroceso del recto medio', 'Blefaróstato', 7, TRUE),
  ('Retroceso del recto medio', 'Lavado de superficie con iodopovidona al 10 %', 8, TRUE),
  ('Retroceso del recto medio', 'Fijación del globo ocular en H12 y H6', 9, TRUE),
  ('Retroceso del recto medio', 'Referencia de conjuntiva con seda 4-0', 10, FALSE),
  ('Retroceso del recto medio', 'Bolsillo conjuntival', 11, TRUE),
  ('Retroceso del recto medio', 'Incisiones relajantes', 12, TRUE),
  ('Retroceso del recto medio', 'Desinserción muscular con tijera Westcott', 13, TRUE),
  ('Retroceso del recto medio', 'Sutura flotante', 14, TRUE),
  ('Retroceso del recto medio', 'Dexametasona subconjuntival', 15, TRUE),
  ('Retroceso del recto medio', 'Puntos epiesclerales', 16, TRUE),
  ('Retroceso del recto medio', 'Antibiótico tópico', 17, TRUE),
  ('Retroceso del recto medio', 'Parchado ocular', 18, TRUE),
  ('Sondaje de vía lagrimal', 'Anestesia local', 1, TRUE),
  ('Sondaje de vía lagrimal', 'Asepsia y antisepsia del área operatoria', 2, TRUE),
  ('Sondaje de vía lagrimal', 'Colocación de campos quirúrgicos estériles', 3, TRUE),
  ('Sondaje de vía lagrimal', 'Dilatación de puntos lagrimales', 4, TRUE),
  ('Sondaje de vía lagrimal', 'Sondaje con sonda de Bowman N.° 2', 5, TRUE),
  ('Sondaje de vía lagrimal', 'Prueba de permeabilidad con solución salina', 6, TRUE),
  ('Sondaje de vía lagrimal', 'Asepsia final', 7, TRUE),
  ('Trabeculectomía', 'Anestesia local', 1, TRUE),
  ('Trabeculectomía', 'Anestesia general', 2, FALSE),
  ('Trabeculectomía', 'Anestesia local peribulbar', 3, FALSE),
  ('Trabeculectomía', 'Asepsia y antisepsia del área operatoria', 4, TRUE),
  ('Trabeculectomía', 'Colocación de campos quirúrgicos estériles', 5, TRUE),
  ('Trabeculectomía', 'Tegaderm', 6, TRUE),
  ('Trabeculectomía', 'Blefaróstato', 7, TRUE),
  ('Trabeculectomía', 'Anestesia subtenon', 8, FALSE),
  ('Trabeculectomía', 'Lavado de superficie con iodopovidona al 2 %', 9, TRUE),
  ('Trabeculectomía', 'Aclaramiento con solución Ringer lactato', 10, TRUE),
  ('Trabeculectomía', 'Cauterización de vasos sangrantes', 11, TRUE),
  ('Trabeculectomía', 'Divulsión de conjuntiva en base de fórnix', 12, TRUE),
  ('Trabeculectomía', 'Tenectomía', 13, TRUE),
  ('Trabeculectomía', 'Esclerotomía en charnela cuadrada', 14, TRUE),
  ('Trabeculectomía', 'Profundización con crescent', 15, TRUE),
  ('Trabeculectomía', 'Mitomicina C tópica durante 3 minutos', 16, TRUE),
  ('Trabeculectomía', 'Apertura de puertos laterales H3 y H9', 17, TRUE),
  ('Trabeculectomía', 'Iridectomía en H12', 18, TRUE),
  ('Trabeculectomía', 'Iridotomía con pinza punch de Kelly', 19, TRUE),
  ('Trabeculectomía', 'Puntos epiesclerales', 20, FALSE),
  ('Trabeculectomía', 'Antibiótico tópico', 21, TRUE),
  ('Trabeculectomía', 'Asepsia final', 22, TRUE),
  ('Trabeculectomía', 'Parchado ocular', 23, TRUE),
  ('Trabeculectomía + retiro de material quirúrgico', 'Anestesia local', 1, TRUE),
  ('Trabeculectomía + retiro de material quirúrgico', 'Anestesia local peribulbar', 2, FALSE),
  ('Trabeculectomía + retiro de material quirúrgico', 'Asepsia y antisepsia del área operatoria', 3, TRUE),
  ('Trabeculectomía + retiro de material quirúrgico', 'Colocación de campos quirúrgicos estériles', 4, TRUE),
  ('Trabeculectomía + retiro de material quirúrgico', 'Tegaderm', 5, TRUE),
  ('Trabeculectomía + retiro de material quirúrgico', 'Blefaróstato', 6, TRUE),
  ('Trabeculectomía + retiro de material quirúrgico', 'Lavado de superficie con iodopovidona al 2 %', 7, TRUE),
  ('Trabeculectomía + retiro de material quirúrgico', 'Aclaramiento con solución Ringer lactato', 8, TRUE),
  ('Trabeculectomía + retiro de material quirúrgico', 'Divulsión de conjuntiva en base de fórnix', 9, TRUE),
  ('Trabeculectomía + retiro de material quirúrgico', 'Tenectomía', 10, TRUE),
  ('Trabeculectomía + retiro de material quirúrgico', 'Cauterización de vasos sangrantes', 11, TRUE),
  ('Trabeculectomía + retiro de material quirúrgico', 'Esclerotomía en charnela cuadrada', 12, TRUE),
  ('Trabeculectomía + retiro de material quirúrgico', 'Mitomicina C tópica durante 3 minutos', 13, TRUE),
  ('Trabeculectomía + retiro de material quirúrgico', 'Apertura de puertos laterales H3 y H9', 14, TRUE),
  ('Trabeculectomía + retiro de material quirúrgico', 'Iridotomía con pinza punch de Kelly', 15, TRUE),
  ('Trabeculectomía + retiro de material quirúrgico', 'Antibiótico tópico', 16, TRUE),
  ('Trabeculectomía + retiro de material quirúrgico', 'Parchado ocular', 17, TRUE),
  ('Trabeculectomía minifiltrante', 'Anestesia general', 1, TRUE),
  ('Trabeculectomía minifiltrante', 'Asepsia y antisepsia del área operatoria', 2, TRUE),
  ('Trabeculectomía minifiltrante', 'Colocación de campos quirúrgicos estériles', 3, TRUE),
  ('Trabeculectomía minifiltrante', 'Tegaderm', 4, TRUE),
  ('Trabeculectomía minifiltrante', 'Blefaróstato', 5, TRUE),
  ('Trabeculectomía minifiltrante', 'Cauterización de vasos sangrantes', 6, TRUE),
  ('Trabeculectomía minifiltrante', 'Profundización con crescent', 7, TRUE),
  ('Trabeculectomía minifiltrante', 'Mitomicina C tópica durante 3 minutos', 8, TRUE),
  ('Trabeculectomía minifiltrante', 'Aclaramiento con solución Ringer lactato', 9, TRUE),
  ('Trabeculectomía minifiltrante', 'Apertura de puertos laterales H3 y H9', 10, TRUE),
  ('Trabeculectomía minifiltrante', 'Inyección de miochol', 11, TRUE),
  ('Trabeculectomía minifiltrante', 'Iridotomía con pinza punch de Kelly', 12, TRUE),
  ('Trabeculectomía minifiltrante', 'Puntos epiesclerales', 13, TRUE),
  ('Trabeculectomía minifiltrante', 'Asepsia final', 14, TRUE),
  ('Trabeculectomía minifiltrante', 'Parchado ocular', 15, TRUE),
  ('Transposición muscular tipo Jansen', 'Anestesia general', 1, TRUE),
  ('Transposición muscular tipo Jansen', 'Asepsia y antisepsia del área operatoria', 2, TRUE),
  ('Transposición muscular tipo Jansen', 'Colocación de campos quirúrgicos estériles', 3, TRUE),
  ('Transposición muscular tipo Jansen', 'Tegaderm', 4, TRUE),
  ('Transposición muscular tipo Jansen', 'Blefaróstato', 5, TRUE),
  ('Transposición muscular tipo Jansen', 'Lavado de superficie con iodopovidona al 10 %', 6, TRUE),
  ('Transposición muscular tipo Jansen', 'Fijación del globo ocular en H12 y H6', 7, TRUE),
  ('Transposición muscular tipo Jansen', 'Puntos epiesclerales', 8, TRUE),
  ('Transposición muscular tipo Jansen', 'Dexametasona subconjuntival', 9, TRUE),
  ('Transposición muscular tipo Jansen', 'Antibiótico tópico', 10, TRUE)
) AS v(procedimiento, tecnica, orden, por_defecto)
JOIN "Procedimientos" p ON p.intervencion = v.procedimiento
JOIN "Intervencion"   i ON i.tecnica      = v.tecnica
ON CONFLICT (id_procedimiento, id_tecnica) DO NOTHING;

COMMIT;
